### ISSUE TITLE
Package description for firmware updates

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LwM2M_for_Developers#1]
Test Case number –int 302 Firmware Update (via alternative mechanism)

Currently the firmware update objects only provides a package URI without any further description such as length, criticality, etc. 

What are the Use Cases for this?

Possible solution is to have an optional resource for package description.

**Comment by jvermillard** [comment]
no feedback, could be closed no?

**Comment by hannestschofenig** [comment]
A manifest about firmware packages should be a topic for LWM2M version 1.1 (rather than v1.0). Some of the content may be defined as new resources but I would prefer to see it in a bigger context, which includes security functionality as well. With http://tools.ietf.org/html/rfc4108 there is also a starting point for such meta-data and it also includes security-related content.

**Comment by ThGarnier** [comment]
New Req (1.1) => to be closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above that New Requirements will be included in version 1.1
