### ISSUE TITLE
Duplicate message delivery in Queued messages

### ISSUE THREAD

**Issue by balsmn** [OpenMobileAlliance/OMA_LwM2M_for_Developers#104]
Hi,

Irrespective of whether Queue-Mode should be revisted or not, as of the fact that it is now in the Spec, I have one question regarding the reliable message delivery.

Spec defines in Section 8.3 "Each request is sent serially to the LWM2M Client, waiting for request to be Acknowledged before sending the next request"

Does that mean sending the unacknowledged messages again is acceptable? (Ack could have been lost but client receives the message twice) . Is it ok to send duplicates and the client could take care of it?

or 

Should LWM2M Server make best effort to deliver the message only once?

**Comment by hannestschofenig** [comment]
Within Queue mode we are mostly interested in the fact that a LWM2M server receives a response to a request before sending out the next request from the queue. In order to determine when the request has been fulfilled the LWM2M server must wait for a response to arrive. A response can be conveyed to the server in two ways: 
 * ACK piggybacking the response, or 
 * separate CON/non-CON containing the response. 

CoAP limits the number of simultaneous outstanding interactions to 1. 

Trying to deliver the request to the LWM2M client may require retransmission of the request but this is taken care of by the CoAP layer itself. Therefore it must not be handled at the LWM2M layer. 
 
If the CoAP layer fails to deliver the request (after several retransmissions) it must notify the LWM2M layer about the failure. The LWM2M server must retain the failed message in the queue and must inform the sender (application) about the failed delivery. The LWM2M server must assume that the LWM2M client is currently unreachable and must not attempt to delivery any further messages from the queue for that LWM2M client until that client contacts the server the next time. 

A LWM2M server might support a feature like a time-to-life to allow an application to indicate how long the message is to be kept in the queue.  A LWM2M server would then remove expired messages from the queue regardless of their delivery status.The API between the LWM2M server and the application is outside the scope of the LWM2M specification.

**Comment by balsmn** [comment]
@hannestschofenig We are currently having a similar discussion about TTL in the Leshan mailing list. From your writing

> The API between the LWM2M server and the application is outside the scope of the LWM2M specification.

TTL could be an absolute time or relative and each application layer will have different requirements on this. Depending on that an application can represent TTL value differently. Do you mean this as API?

> A LWM2M server might support a feature like a time-to-life to allow an application to indicate how long the message is to be kept in the queue. 

are you considering to specifiying TTL in LWM2M? If yes, I have some follow-up questions.
* is TTL applicable for individual messages or for all messages of a given LWM2M client?
* can TTL also be valid for non-queue messages?

**Comment by balsmn** [comment]
> If the CoAP layer fails to deliver the request (after several retransmissions) it must notify the LWM2M layer about the failure. The LWM2M server must retain the failed message in the queue and must inform the sender (application) about the failed delivery. 

I don't think the Server must inform the application about the failed delivery due to coap timeout. It is for this reason we have queue mode where the application doesn't care when it is delivered to LWM2M client but wants the failed messages to be retried when the client is reachable again.

**Comment by balsmn** [comment]
I think our initial question is still not answered.

Yes CoAP layer retries the messages that could not be delivered and notifies the LWM2M layer when a certain retry count has been reached. 

The question was for the scenario "ACK or a separate CON containing the response gets lost" and say the LWM2M layer gets notified by CoAP layer after the retry count has been reachend. Now the message is in the queue and will be sent again when the client is reachable. From the client presepective it is clearly a duplicate.

will the client be able to handle these duplicates?

**Comment by msangoi** [comment]
@balsmn When the message is sent again after being queued, this is a new CoAP request with a new message ID  (not a retransmission of the initial request). So I don't think there is a duplication issue.

**Comment by balsmn** [comment]
@msangoi thats exactly the problem. Say we have a execute operation to toggle a switch. Now when the ACK for the first send gets lost, in queue mode, the same request with a new message ID will be sent. Imagine the implication on the client side. You will not get the desired behaviour as a result of that execute operation executed twice.

**Comment by msangoi** [comment]
Ok I see your point. Note that you have the same issue if you are not in queue mode. But in that case, the application layer can handle the delivery failure by checking the switch state (to reuse your example) before retrying the execute operation.
If you want to solve this in queue mode, I think that the LWM2M server should not retain the message in the queue in case of delivery failure. The application will be notified and will be in charge on re-enqueing the message if needed.

**Comment by balsmn** [comment]
I agree with you regarding non-queue mode. Queue mode is used by clients which are not online all the time. So when a application layer sends a message, it expects _eventual delivery_ and don't expect a delivery failure response after first try as client is offline. What I was trying to bring here is that on the server side, it is simply impossible to guarantee _at least once_ delivery. So I was thinking that if the LWM2M Client has a mechanism to detect duplicates ignoring MID, then it could solve the problem.

**Comment by msangoi** [comment]
If the client is registered in queue mode, the server will wait for the next register/update/notify before sending the request. So the client is expected to be online at that time, and a delivery failure (e.g. because of network issues) can be handled by the application.

**Comment by boaks** [comment]
>  Say we have a execute operation to toggle a switch. 

Just don't design your application in such a way!
See #78.

**Comment by balsmn** [comment]
I agree. It was just an example to highlight that the duplicate message delivery can't be avoided at LWM2M Server side.

**Comment by sbernard31** [comment]
The spec say (§8.3):
 _"If a request is unsuccessful then the request returns to the queue that has been previously fetched, to the same position in the queue."_
I'm not sure this is the good way to do.

In a "normal" case the client must wait MAX_TRANSMIT_WAIT (#98) before to pass offline.
This means thats the case where request will timedout after all retransmission should be the exception.
From my point of view, we must leave the application layer handle the case and so remove the request from the queue. I think the spec must be changed.

**Comment by boaks** [comment]
Assuming the "client aliveness" is the dominant factor for successful communication, you are right.

Assuming the "infrastructure (NAT/Firewall)" is the dominant factor for successful communication, I think you are wrong ;-).

**Comment by sbernard31** [comment]
The CoAP retransmission should limit the "infrastructure" issue ? If not we should seriously ask ourself if LWM2M over UDP could really works with NAT/Firewall :-p

**Comment by hannestschofenig** [comment]
A few responses to statements made above: 

> Are you considering to specifiying TTL in LWM2M?

No. This TTL value would be part of the API used between the LWM2M server and the application server, which is currently outside the scope of LWM2M. 

> So when an application layer sends a message, it expects eventual delivery and don't expect a delivery failure response after first try as client is offline.

Since the API between the LWM2M server and the application server is not specified in the spec it is hard to say what some vendors will do. Maybe they will notify you that there have been problems with the delivery immediately; maybe they only tell you once various timers have expired. 

> It is simply impossible to guarantee at least once delivery. 

It is indeed impossible to make guarantees when devices come & go. From an application developer it is, however, desirable to have a consistent view of what is going on even though the tasks of communicating this view is outside the scope of the LWM2M spec right now. So, if the LWM2M server is unable to communicate with a specific device then this information should become available to the application.

**Comment by hannestschofenig** [comment]
Covered in https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/115

**Comment by ThGarnier** [comment]
According to the last CR117 included in the Oct16 TS,  issue can be closed

**Comment by Megan-OMA** [comment]
Issue closed per Hannes' and Thierry's comments above
