### ISSUE TITLE
Queue mode and notifications

### ISSUE THREAD

**Issue by jvermillard** [OpenMobileAlliance/OMA_LwM2M_for_Developers#115]
In the spec under the "Queue Mode Operation" paragraph:

> When the LWM2M Server receives a message from the Client (e.g. a notification or a registration update), it checks its request queue for the LWM2M Client and performs the needed CoAP operation(s) (e.g. GET, PUT, and POST).

So does a notification without a registration update is allowed in queue mode?
In the example figure there is a registration update before the notification, but the previous paragraph let us think it's allowed to send a notification without a registration update.

There is two way to implement it:
- do a registration update when the device wakes up for sending the notification, i.e. the device sends a registration update once before it starts sending one or more notification
- device wakes up and immediately sends the notifications at will, and the server is free to consider the device is online and updates the registration lifetime and ip address.

**Comment by sophokles73** [comment]
Here are my suggestions for changing section 8.3.:

Paragraph 2 currently reads: 
> When the LWM2M Client has registered with Current Transport Binding and Mode parameter including “Q” (see chapter 5.4), The LWM2M Server does not immediately send downlink requests on the transport layer used in Queue mode, but instead waits until the LWM2M Client is online on the transport layer.

but should read:

"When a LWM2M Client has registered with Current Transport Binding and Mode parameter including “Q” (see section 5.4), the LWM2M Server MUST not send downlink requests immediately to the client on the transport layer but instead the server MUST wait until the LWM2M Client has become online again on the transport layer."

Paragraph 3 currently reads:
> The LWM2M Client lets the LWM2M Server know it is awake by sending a registration update message as a Confirmable message. The LWM2M Server then makes any queued requests to the LWM2M Client in a serial fashion. The LWM2M Client MUST wait at least ACK_TIMEOUT [COAP] seconds from the last CoAP message it sent to the LWM2M Server before intentionally going offline. If the LWM2M Server is not successful in sending a request – i.e. Server gives up on receiving an acknowledgment or reset -, then it stops emptying the queue and keeps the request for the next time the LWM2M Client is online.

but should read:

"A LWM2M Client MUST send a registration update message as a confirmable message (CON) to the server after it has woken up before sending any additional notifications for observed resources. The server SHOULD use the information conveyed in the update request to update its record of the clients registration as described in section 5.3.2. The LWM2M Server then SHOULD start to send any pending queued requests to the LWM2M Client. The server MUST send the requests to the client in a serial fashion only, i.e the server MUST NOT send the next request to the client before it has received the response for the previous request from the client.

The LWM2M Client MUST wait at least ACK_TIMEOUT [COAP] seconds after it has sent its last CoAP message to the LWM2M Server before it MAY intentionally go offline (asleep). If the LWM2M Server is not successful in sending a request, i.e. the Server gives up on receiving an acknowledgment or reset, then it MUST stop emptying the queue and MUST retain the pending requests in the queue in order to deliver them the next time the LWM2M Client becomes online again (indicated by an update registration request)."

**Comment by boaks** [comment]
According LWM2M TS 8.2.1, Firewall/NAT, `Queue Mode` is not only intended for sleeping devices, it's also intended for devices behind such a firewall/NAT. Therefore it may be required to generalize the "`woke up`". I would guess, a client, which is indicating Q, must use such an `update register` after any periode of "not exchanging messages".

There a also other discussions/issues about the queue mode. 

https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/98
https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/33
https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/32

#32 TIMEOUT for client to go to sleep:
if the client requires to go to sleep for power-reduction, I assume that no timeout will handle this efficient enough. So there should be "server ready" message indicating the client device, that it may go to sleep.

The wording "The LWM2M Server then SHOULD start" may be interpreted as sequence:
1. client register update
2. client notifies
3. server request
But I don't see, how the server knows, that the client is ready with notifies.

**Comment by boaks** [comment]
Using "piggybacked" responses, the terms ACK or Response are equal. But maybe, if this changes, it may be better to use ACK instead of Response in

> The server MUST send the requests to the client in a serial fashion only, i.e the server MUST NOT send the next request to the client before it has received the response for the previous request from the client.

> it has received the ACK for the previous CON message from the client.

**Comment by jpradocueva** [comment]
@boaks 
This is the list of open issues reported to DM on this topic of queue mode:
* [#104](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/104) - Duplicate message delivery in Queued messages
* [#98](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/98) - Queue mode and timeout for offline
* [#80](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/80) - Queue mode and REGISTER
* [#69](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/69) - Persistence of downlink requests in queue mode
* [#33](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/33) - Define "request is unsuccessful" for 8.3 Queue Mode Operation

The DM group agreed to open a discussion on these issues using the private GitHub repository.

**Comment by hannestschofenig** [comment]
In general it should be acceptable that a LWM2M server uses a notification sent by the client to update extend the lifetime and to trigger emptying the queue. With devices operating in Queue mode it is quite likely that IP address or port numbers change while the device is asleep. Therefore, a notification sent by such a device after it wakes up (with the changed IP address and port number) will be discarded by the LWM2M server based on Section 5.3.2 'Request/Response Matching Rules' of CoAP. 

The proposal therefore is: If a notification is processed by the LWM2M server then the LWM2M Server MUST update the lifetime of the client registration to the original lifetime value.

The server start to send queued messages to the client if it receives such a notification. In such case it is not required for the client to also transmit a registration update message.

If the LWM2M client operates in an environment where it is unable to determine whether its IP address and port number has changed then it must send a registration update message whenever it wakes up in order to convey its potentially changed IP address / port to the LWM2M server.

Note: Because of the way how CoAP is specified, existing observations will be cancelled [implicitly] whenever the LWM2M clients IP address and/or port changes. The LWM2M server is not mandated to re-establish observations in such cases. It is the responsibility of the application to determine whether it is desirable to reestablish an observation or whether the application should fall back to polling. The LWM2M server may provide information back to the application about changes in IP addresses and ports. This functionality is, however, outside the scope of the LWM2M specification.

**Comment by boaks** [comment]
> Therefore, a notification sent by such a device after it wakes up (with the changed IP address and port number) will be discarded by the LWM2M server based on Section 5.3.2 'Request/Response Matching Rules' of CoAP. 

I'm not sure, if we should rely on that, because Californium was changed to use **only** the **token** and **not** the **endpoint** to match request/response pairs (violating 5.3.2, topic 1) 

http://dev.eclipse.org/mhonarc/lists/cf-dev/msg00390.html

https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/71

**Comment by hannestschofenig** [comment]
If the Californium implementation uses a different way to match an incoming packet to already established state then it violates the processing rules of CoAP. It would be interesting to discuss on the IETF CoRE mailing list whether others have encountered similar problems. If that's the case, then an errata should be filed or the RFC revised. 

It turns out that the real problem isn't even at the layer of CoAP but with the underlying DTLS / TLS connection. If the LWM2M server receives a DTLS / TLS record layer packet with a changed IP address and port then such a packet will be rejected since there is no other information in the header to find the appropriate security context. We have tried to address this aspect with a separate draft -- see Section 4 of https://tools.ietf.org/html/draft-fossati-tls-iot-optimizations-00

**Comment by boaks** [comment]
> If the LWM2M server receives a DTLS / TLS record layer packet with a changed IP address and port then such a packet will be rejected since there is no other information in the header to find the appropriate security context.

Sure. therefore, if your usage is faced a potential endpoint change, any endpoint may set up a "last communication timeout" (say 30s) and, if that expires, a "DTLS resume" is required to ensure, that the CoAP reponse / Notify reaches the destination.

By the way, this then violates CoAP RFC 7252, 9.1.2 Request / Reponse layer

> The following rules are added for matching a response to a request:
> The DTLS session MUST be the same, and the epoch MUST be the same.
 
My personal conclusion at that point is:
- RFC 7641 is more "extending the lifetime of a request" to a few minutes, 
   if changes are reported very frequently (e.g. progress indicator).
- It's NOT usable for a general reporting, especially with long silent periods (sleeping devices)
- Therefore it may be required to add a new "LWM2M interface" (similar to "registration") for less frequently events.

**Comment by sbernard31** [comment]
1. do a registration update when the device wakes up for sending the notification, i.e. the device sends a registration update once before it starts sending one or more notification
2. device wakes up and immediately sends the notifications at will, and the server is free to consider the device is online and updates the registration lifetime and ip address.

If the 2. solution is chosen, I suppose registration lifetime and IP address should be updated not only for notifications but for all responses.

**Comment by boaks** [comment]
But "2. solution" with a changed ip  address is a **violation** of CoAP RFC7252 5.3.2!

So only do that, if 
a. it's explizitly stated in LWM2M, that the RFC is broken, so that everyone gets aware, that LWM2M requires a special CoAP implementation.
or
b. discuss that in CORE and change the RFC (and in consequence "all" other implementations should then follow the RFC).

So I'm really sorry (and potentialy to frank):

If LWM2M should be a interoperatable, `2.` is **NO** solution!

**Comment by jvermillard** [comment]
@boaks I don't see where it's a violation of 5.3.2, specifically if it's the same (possibly resumed) dtls session, I think we can assume it's the same identified endpoint.

**Comment by boaks** [comment]
So just add the DTLS requirement to "2. solution".
Without DTLS I still think it's a violation of RFC7252, 5.3.2.

**Comment by sbernard31** [comment]
Personally, I prefer the 1. solution too.
(I'm just saying that if the 2. solution was chosen we should be coherent and handle notifications and response on the same way)

**Comment by dnav** [comment]
Note that with the current TS, the registration lifetime is updated only when receiving a registration update. So the .1 solution is the safer way for a waking up device until @hannestschofenig proposal ("If a notification is processed by the LWM2M server then the LWM2M server MUST update the lifetime of the client registration to the original lifetime value.")

Regarding 5.3.2 violation:
When using UDP, a Client should send an update if its IP address changed. So for the Server, it is identified by its registration and not by its IP address. And the notifications can be matched to the observation request.
With DTLS involved, my understanding is that the registration update is not required as the endpoint is identified whatever its IP address.

My 2cts

**Comment by boaks** [comment]
"1. solution" would require to potentially change the "ip address" for the observes as well.
it's then just triggered in a "more controllable" way.

But just to state it again:
I think  RFC7641 maps only some parts of the reporting interface well.
For the "rare events from sleeping devices" a client-side request containing the "rd/location", the resource-path and the payload may do a better job.

**Comment by hannestschofenig** [comment]
I just posted a (longer) email to the IETF CoRE mailing list about the topic of IP address and/or port change, see https://www.ietf.org/mail-archive/web/core/current/msg07813.html 

The biggest problem with an IP address and/or port change is at the DTLS layer where the new packet will be discarded and a new handshake needs to be executed to re-establish the security context. Afterwards, the client needs to re-register again.

**Comment by hannestschofenig** [comment]
We discussed the topic of Queue Mode at the OMA interim meeting in Paris and merged all issues related to this topic in one CR. Here is the proposal: 
http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2016/OMA-DM-LightweightM2M-2016-0117-CR_queue_mode_clarification.zip

I believe the most important change in view is to avoid speaking about queues. See Queue Mode more as a way for the client to inform the server that it may go offline for an extended period of time and that the server needs to take this into account. No talk about queues anymore since those are outside the LWM2M specification.

**Comment by boaks** [comment]
Thanks! Very good cleanup!
One additional proposal (from my note above https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/115#issuecomment-225190310):
Having a server side indication message, that the server is ready, would allow the client in the majority of the cases to save energy.

**Comment by hannestschofenig** [comment]
I agree that this would be a useful optimization and we even discussed it during the meeting. The conclusion was then to push this type of additional optimization to LWM2M v1.1 since we really want to finalize LWM2M version 1.0 ASAP.

**Comment by ThGarnier** [comment]
According to the last CR117 included in the Oct16 TS ussue can be closed (New  Requirement Label added for futher usage)

**Comment by Megan-OMA** [comment]
Issue closed per Hannes' and Thierry's comments above
