### ISSUE TITLE
Definition of EXECUTE / could the result contain payload?

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#118]
According LWM2M TS 20160531

Section 5.4.5 Excute doesn't mention the possibility of returning a payload.
It expresses, that `execute` is intended to "initiate some action".

Section 8.2.4 mentions

    "Note that the behaviour of the “Execute” operation, whether it uses arguments and how those
     are interpreted, and how it **returns values** is specified in the Resource description of the
     Object."

In table 23, only the result code 2.04 is listed, so the result doesn't contain a payload.

Having a result paylod (2.05) would enable `execute` to return content depending on the parameter. Having "historic data" in mind, I would appreciate, if **return values** are supported.

**Comment by boaks** [comment]
According the introduced "none" data type (Appendix C), I guess "return values" doesn't include "payload" ;-(.

**Comment by ThGarnier** [comment]
In TS 1.0, Executable resources doesn't return any payload. So the result produced by a triggered Executable resource must be reported using an another Resource (few examples in the  Core Spec Objects e.g. Firmware update). This feature - if really needed - could be discussed/study in a next release timeframe.

**Comment by boaks** [comment]
My intention was a very "efficient way" to read historic data (one request, not two).

But though it's an optimazition, I sure agree, that the discussion can be moved to the next release.

**Comment by sbernard31** [comment]
I revive this topic because I really find the specification confusing.
Currently in Leshan we don't support this, but we have this kind of needs and we find the specification understandable in the way this is allowed.

The LWM2M specification 1.0.x and 1.1 says : 
> Note that the behaviour of the “Execute”operation, whether it uses arguments and how those are interpreted, and how it returns values is specified in the Resource description of the Object.

So what means how it returns values, if return values is not allowed ?

About the 2.04 response code the [CoAP rfc](https://tools.ietf.org/html/rfc7252#section-5.9.1.4) says :
>  This Response Code is like HTTP 204 "No Content" but only used in
   response to POST and PUT requests.  The payload returned with the
   response, if any, is a representation of the action result.
