### ISSUE TITLE
message payload / content type

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#125]
Is there any reason, why only **responses** `MUST` specify the content type (OMA-TS-LightweightM2M-V1_0-20160802-D, 6.4)?

If the **request** contains a payload (write, PUT), why is that requirement not marked as `MUST` for that case?

**Comment by ThGarnier** [comment]
section 5.4.3 (Write) it is said (V1_0-20160802-D) :  "The request includes the value to be written in the corresponding Plain Text, Opaque, TLV or JSON format according to the Content-Format option which MUST be specified [CoAP]."   so there is no issue.

But you are right !! section 6.4 should reflect this, and not be focussed on the response message only ;
it is certainly because few months ago, this section was "GET access oriented" ! some scories are remaining : must be improved . Thanks!

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above for this to be addressed 11-Oct-2016
