### ISSUE TITLE
Outdated IETF references

### ISSUE THREAD

**Issue by hannestschofenig** [OpenMobileAlliance/OMA_LwM2M_for_Developers#134]
Originally raised by Brian Raymor Brian.Raymor@MICROSOFT.COM. 

> There are outdated IETF-related references in OMA-TS-LightweightM2M-V1_0-20160802-D:
> [CoRE_Interface]    Z. Shelby, M. Vial, “CoRE Interfaces”, draft-ietf-core-interfaces-01, Nov 2013 
> [OBSERVE]   Hartke, K. “Observing Resources in CoAP”, draft-ietf-core-observe-10 (work in progress), September 2013. 
> 
> [CoRE_Interface] is now draft-ietf-core-interfaces-05 - https://datatracker.ietf.org/doc/draft-ietf-core-interfaces/. I’d note that it’s milestone is March 2017 - https://datatracker.ietf.org/wg/core/charter/ - 
> 
> [OBSERVE] is now RFC7641 - https://tools.ietf.org/html/rfc7641

The CORE interface draft was split into two documents recently, namely 
- draft-ietf-core-interfaces-05  
- draft-groves-core-dynlink-00 
  and someone would have to check what changes have been made since version -01 and whether those changes have an impact on the LWM2M specification. 

Furthermore, a normative reference in the LWM2M specification raises the question about what happens when version 1.0 of the LWM2M specification gets finalized. Is it possible to have normative references to ongoing work in OMA specifications (and what does this mean for implementers)?

**Comment by hannestschofenig** [comment]
The correct reference for SMS-DTLS would in the meanwhile be Appendix A of RFC 7925 (see https://tools.ietf.org/html/rfc7925) since we moved the text over there. Hence, this issue could be addressed fairly easily. 

More difficult is the reference to SENML since the specification is also still work in progress.

**Comment by boaks** [comment]
> Furthermore, a normative reference in the LWM2M specification raises the question about what happens when version 1.0 of the LWM2M specification gets finalized. Is it possible to have normative references to ongoing work in OMA specifications (and what does this mean for implementers)?

Very good question!
It was my very first impression when I started to work on LWM2M issues several months ago, that there are references, which are not frequently updated in LWM2M TS. And that rises also the question, if this implies to "use old implementations" of lower layer functionality.
But my impression of the "reality" is more, that the implementations also do not strictly align to specific specification versions and more on the currently usage. Or even be more precise, some implementation problems seem to be fed back to the specifications and therefore matches ahead.
But there are no guarantees, everyone has to test it according his requirements. And the question of interoperability stays open.

**Comment by hannestschofenig** [comment]
The problem with using "old" versions of the specification is that there is no assumption that each version of an IETF draft is actually complete nor implementable. The understanding in the IETF is that a draft is a work in progress documented and should not be cited other than that. There is also no assumption that higher version numbers of a draft are less likely to change before the become an RFC.

**Comment by boaks** [comment]
draft-ietf-core-block-21 now RFC 7959 ?

**Comment by brianraymor** [comment]
@boaks - Yes - block is now [RFC7959](https://datatracker.ietf.org/doc/rfc7959/)

draft-groves-core-dynlink-00 was recently adopted as a WG item in the IETF CoRE WG - the new reference to the work-in-progress - https://datatracker.ietf.org/doc/draft-ietf-core-dynlink/

**Comment by brianraymor** [comment]
Joaquin provided a reference to policy:

http://member.openmobilealliance.org/ftp/Public_documents/REL/Permanent_documents/OMA-ORG-ReferencingPolicy-V1_0-20110524-A.zip

6.3 Making a reference
When there is a reference to a document that is not considered stable in the referenced organization, a note should be added to the OMA Specification making such reference, that clearly states that the referenced document is not stable and, if possible, provides an indication of the potential date when it may become stable, and in the case of specific reference (see below), with the version number of the referenced document. 

The IOP working group should review the status of any normative references in the specification when making their interoperability validation preparations, and cooperate with the originating working group as appropriate in a pragmatic manner.

An OMA document being submitted for final approval, e.g. following the interoperability validation of a candidate specification, containing any normative reference that is not stable should be reviewed and a path to updating them should be identified if still necessary at the time of the update.   

A statement should be inserted as part of the normative references section of the normal document template stating that attention should be given to explicit normative references within the referenced document since by extension any conformance requirements in the sub-referenced document are binding on the OMA Specification.  The working group should proceed to review any explicit normative references in the referenced documents.

Normative reference should not be made to informative documents, and instead an informative reference should be made.

**Comment by ThGarnier** [comment]
According to Oct16 F2F meeting discussion, WG is aware of having to track that kind of important issue => To Be Closed

**Comment by brianraymor** [comment]
It's not simply tracking, the references need to be annotated?

_a note **should** be added to the OMA Specification making such reference, that clearly states that the referenced document is not stable and, if possible, provides an indication of the potential date when it may become stable, and in the case of specific reference (see below), with the version number of the referenced document._
