### ISSUE TITLE
More Discover ambiguities.

### ISSUE THREAD

**Issue by sznaider** [OpenMobileAlliance/OMA_LwM2M_for_Developers#135]
Hello again, I have some further questions about the Discover operation.

First of all, some definitions:
- Resource is **present**, if one can perform some LWM2M operation on it, and this operation does not yield 4.04 Not Found response.
- Resource is **possibly-present**, if one can perform some LWM2M operation on it, after which it is **present** (e.g. Write on Lifetime that was previously undefined)

Now questions:
1. Does **possibly-present** definition correspond to the definition of "implemented" used in spec in the context of Discover?
2. I believe that not every Resource must be **present** for given Instance. In such case, where some of the Resources are not **present** what should Discover do? Should it return all **possibly-present** resources, or **present** resources only?
3. Suppose we are performing Discover on some Object, let's say `/1`. Can the following output be valid?
   `</1>,</1/0>,</1/0/3>`<br/>
   Note the superflous `</1/0>` -- we are able to tell that Instance `0` exists for this Object by looking only at `</1/0/3>`. Spec says that we should return all Object Instances and the list of implemented Resources, so theoretically this output meets the criteria... Does it?
4. Besides, can one skip `</x/y>` part for Multi Instance Objects, and refer only to the Resource paths? (i.e. `</x/y/z>`)
5. (Discover on Object) What if there is an Instance with no **possibly-present** resources? Could `</1>,</1/2>` ever happen? For example assumming there is some Object that dynamically changes list of its Resources.
6. Is it even valid for Instance to have no **possibly-present** Resources?
7. (Discover on Object Instance) Is `</1/2/3>` invalid? Or we are allowed to omit the Instance path, if it is implied by its Resource list and has no Attributes? (i.e. instead of `</1/2>,</1/2/3>`)
8. Shall Discover return default attributes assigned to the Server? I.e. for output `<1/2/3>;pmin=1`, can `pmin` be derived from the Server defaults (Default Minimum/Maximum Period Resources)?
9. Should Discover even return default `pmin/pmax` values?
10. In case of multi-server environment Attribute list includes `ep` with the SSID of a server that has set Attributes. What happens when there are two servers, but only one of them sets any Attributes? Should Discover return `</1/2/3>;ep=1,</1/2/3>;ep=2;pmin=1` or maybe `</1/2/3>;ep=2;pmin=1` is sufficient?

**Comment by dnav** [comment]
I don't get your concept of "possibly-present". A resource is either present or not. Having a valid value is a different matter.

**Comment by kFYatek** [comment]
@dnav, as I work on the same team with @sznaider, let me answer you.

The problem we have is that we don't exactly understand the terms **supported**, **implemented** and **present**, which are referenced throughout the specification. What are the relation between those? As we currently understand it:

- **supported** and **implemented** are - at least for the LWM2M Client - more or less synonymous, and mean that the device has code necessary to handle those Resources being *present* in the data model - but it does not automatically mean that such Resource will be *present* in all Instances of an Object
- **present** means that a specific Object Instance of a specific Object has a specific Resource - the state of *presence* of a specific Resource might be different for different Object Instances
- a Resource becomes **present** when it is given a value - either by the Create or Write operation, or by some external event - e.g. a "signal strength" Resource is given a value when an appropriate network interface becomes connected
- a Resource that is **supported** and Mandatory should always be **present** - although there are some discrepancies in the specification, e.g. Table 6 in section 5.3.1 (Register) reads:

  > If Lifetime Resource does not exist in a LWM2M Server Object Instance (...)

  even though the Lifetime Resource is defined as Mandatory in Appendix E.2.

Is this interpretation correct? If so, @sznaider's concept of **possibly-present** means "a resource that might ever be **present** on a given Client".

Since the wording in 5.4.2 (Discover) refers to "the list of *implemented* Resources", we are unsure whether we should return the list of Resources that are **possibly-present** (which might, according to our interpretation, become **present** after a Write operation or some external event) or **present**.

**Comment by dnav** [comment]
Thanks @kFYatek I can understand the confusion. It appears there are some improvements needed in the TS glossary.

Here is my personal view on this:

- **supported** is relative to operations and protocol features. In the TS it is not associated to resources.

- **implemented** usage is indeed confusing. We need to replace it on a case by case basis.

- I agree with @sznaider's definition of **present**: "Resource is present, if one can perform some LWM2M operation on it, and this operation does not yield 4.04 Not Found response."

- A discovery operation will return all the present resources under the specified URI.

- A mandatory resource is always present. (From a protocol point-of-view, I can not see cases where it may have not have a value as a Create operation must include it.)

- Optional resources may or may not be present.

So to answer @sznaider's questions:
1. The possibly-present context does not exist in LWM2M.
2. A discovery operation returns all the present resources of a given Object instance.
3.  </1>,</1/0>,</1/0/3> is indeed a valid output but </1> and </1/0> should be returned only if attributes are attached to them.
4. The client should return only resource paths to a discovery operation **if** there are no attributes to the Object or Object Instance.
5. The possibly-present context does not exist in LWM2M and empty Objects are kind of pointless.
6. idem
7. </1/2/3> is valid
8. and 9. I would say no but it needs to be specified explicitly in the TS.
10. You need to include the Server Short ID as the attributes are different for the other Servers (default values).

I hope this helps.

**Comment by kFYatek** [comment]
There is still some confusion about the exact meaning of "present", but I will address it in a separate ticket, as it is outside the scope of Discover.

However, regarding Discover - the current understanding of Discover mandates that Resources shall be enumerated per Object Instance - which also implies that if no Object Instances exist for a given Object, no information about Resources is returned.

This would mean that the LWM2M Server has no means to discover the set of implemented resources, i.e., it cannot safely call the Create operation, including values for writeable Optional Resources in the payload, because it has no information whatsoever about Optional Resources implemented on the client device.

Is this intended? Or are we missing something?

**Comment by ThGarnier** [comment]
It’s already a long thread, so difficult to find an efficient way to answer and to clarify the things : I will split my comment in 2 parts : 
a)	Firstly pointing out the few TS 1.0 inconsistencies and confusing wording , thank’s !! we will work on them if it is not the case yet. 
I will address that points – with the LWM2M TS 1.0 spirit in mind (with TS References)  - but in rejecting introduction of vocabulary which is not already used in the TS 1.0; it introduces still  more confusion (however I agree, TS 1.0 wording has to be improved for sure, work is on going);
b)	b1 & b2 An answer with some   focus on which question is addressed  (there are several in this single issue  )

a)	Yes : in TS 1.0, there is still confusing terms as “supported”, “implemented”  (present I don’t see it, if so, it is really marginal)

As noted by dnav :  “supported” is (mainly) relative to operations & protocol features not to Resources,  of course you could find some counter-examples ( to be corrected in TS but again marginal) .There is discussion to replace the term “implemented” 
The term “implemented” is mainly used in TS for a Resource which is defined/specified  in a given Object,  and for which an instance (single or multiple) of that Resource is contained in a specific Instance of that Object (and can be addressed from the Server by the path /Object/Instance/Resource):
As illustration: a Client can support the  LwM2M Object Server ID:1 (in which 9 Resources are specified [0-8]) with 2 instantiation ID:0 and ID:1 
(I agree there is an issue on Resource 1 Lifetime and section Table 6 section 5.3.1) 
The first Object Instance ID:0  (/1/0) could have 5 Resources instantiated (implemented) :0,1,6,7,8 while the second Server Instance could have 9 Resources instantiated: 0,1,6,7,8 and also 2 &3. 
So in TS 1.0 : 
•	A Resource defined as Mandatory in the Object specification means, this Resource is instantiated as soon as an Instance of that Object is created (ex: mandatory Resources 0,1, 6,7,8 of the Server Object ).
•	A Resource defined as Optional in the Object specification means, an Instance of this Resource may be part or not of a particular Instance of that Object (ex : Optional Resources 2 & 3 are instantiated in Server Object Instance 1 and not in Server Object Instance 0)
              In LwM2M TS 1.0, this resource Instantiation takes place when the Object is created; a possibility exists also for the Optional resources to be instantiated at other moment (section 5.4.3) . In both cases the rules defines in the Authorization section applies ( section 7.3.2, 7.3.2.4)
b)	b1).Regarding the 10 points , in addition to dnav  answer :
3. with the Server ID:1 of your example request  and my example  above : 
The client should answer (if no Attribute at Object & Instance levels) 
   </1/0/0>, </1/0/1>,</1/0/6>,</1/0/7>,</1/1/0>, </1/1/1>,</1/1/2>,</1/1/3>,</1/1/6>,</1/1/7>,</1/1/8>
5. in theory,  an Object Instance with no Instantiated Resource and without Attributes defined at the Object Instance level, will answer to a Discover Command on the particular
Object Instance ID as target, with an empty payload (but without error, which will be the case if the Object Instance doesn’t exist).
Really academic example 
8. & 9.as dnav says, it is not explicitly said in TS; so that means both are allowed; so there is no added-value to discover a default value, the Server knows the spec (xml) ; better is to omit it (save bandwidth)   


b2)  Right! if the Object has no Instance, it will have no entry in the payload of the Discover command (through registration the Server knows it is supported by the Client) .

However, already having an Instance of an Object, even doesn’t solve your issue.
I would say, if an Object specifies 10 Optional Resources, and an Instance of the Object has been created with only 8 of them; what about the 2 others ? maybe the Client is able to instantiate them, ..or not.
One way in TS 1.0 is to create a new Instance of that Object, with the expected Optional Resources. The TS 1.0 specifies (7.3.2.4 ) if the Client is not able to instantiate few Optional Resources (but it has the access rights to do) , it will ignore them  (OK !! the TS should be improve to say that elsewhere  ). So after successful creation, a Discover on that Instance will reveal which specific resources have been instantiated.. or not. 

Many thanks to point out these ambiguities

**Comment by ThGarnier** [comment]
hum !! the illustration for point 3. has been not copied in that ????!!! editor :
` </1/0/0>, </1/0/1>,</1/0/6>,</1/0/7>,</1/1/0>, </1/1/1>,</1/1/2>,</1/1/3>,</1/1/6>,</1/1/7>,</1/1/8> `

**Comment by ThGarnier** [comment]
Please look at the nex Nov16 TS 1.0 release, and if any remaning issues , please adress them in separate issues . many thanks

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above
