### ISSUE TITLE
Observation lifetime, registration interface, and DTLS sessions

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#137]
Though https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/71 started a discussion about observation lifetime according the registration interface, I got aware, that if the DTLS session was broken and a new DTLS session is created, this will also stop the notifies (caused by the definition, that a request and a response mus share teh same DTLS session and epoch for security reasons). 
Therefore, a client, which get's aware of a new DTLS session seems currently to be forced to do a registration and not using a "register update".
So the LWM2M TS should add more details of the influence of the DTLS to the upper layers.

**Comment by DanielMaier-BSI** [comment]
Any other thoughts about this issue?

Here are mine:

An alternative approach to re-register the client after new DTLS handshake would be that the server needs to be aware of the new handshake from lower levels (DTLS layer) and re-establish the observe relations. 

Another alternative would be to relax the requirement that the response needs to be in the same DTLS session and epoch to the requirement that each response needs to be from the same identity as the request was sent to. I suppose this has no security implications because we have always client authentication in LWM2M scenario anyways. But I think we should not differ CoAP specification for LWM2M use case, because this will be problematic when someone uses a CoAP library that is not aware of this.

To be honest I would prefer the re-register solution mentioned above by boaks.

However, I think one of the approaches need to be specified in LWM2M TS to ensure that the server (or client) has predictable behavior.

**Comment by dnav** [comment]
This issue will be addressed in the next TS.
A new DTLS session will explicitely require a new registration.

Regards,

**Comment by hannestschofenig** [comment]
There is typically a reason why a DTLS session needs to be re-established. An example is an IP address change or an expired NAT binding. In such a circumstance a new re-registration is needed since the LwM2M server also needs to be aware of the new IP address and potentially the port number allocated by a NAT along the path. Additionally, there are the requirements from the IETF RFCs that the same DTLS session / epoch be used. 

Hence, there is nothing really to change at the level of the LwM2M specification. Instead, new work needs to be done in the IETF (with the connection ID) and fixing the text in the CoAP/Observe RFCs are necessary.

**Comment by boaks** [comment]
> Therefore, a client, which get's aware of a new DTLS session seems currently to be forced to do a registration and not using a "register update".

OMA-TS-LightweightM2M-V1_0-20170208-A, 5.5.1, contains:

> The LwM2M Server MUST re-initiate observation requests whenever the LwM2M Client registers.
> ...
> Note: When a LwM2M Client deregisters, the LwM2M Server should assume past states are nullified including the previous observations.

OMA-TS-LightweightM2M-V1_0-20170208-A, 8.2.4, contains:

> When a new DTLS Session is started, or in NoSec mode when the LwM2M Client IP address changes, the Client MUST register again to the LwM2M Server.

So the TS contains in the meantime the clarifications.
