### ISSUE TITLE
Define relation of "Factory Reset" /3/0/5 (E.4) and "bootstrap"

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#147]
According LWM2M TS, E.4 LWM2M Object, /3/0/5 defines a factory reset.

> Perform factory reset of the LWM2M Device to make the LWM2M Device have the same configuration as at the initial deployment.
> 
> When this Resource is executed, “De-register” operation MAY be sent to the LWM2M Server(s) before factory reset of the LWM2M Device.
> 
> LWM2M Server(s) before factory reset of the LWM2M Device.

So, is this intended to reset information set by a bootstrap server?
Should a "purged" "LWM2M Bootstrap Server Account" (see 5.2) be "recreated"?

**Comment by dnav** [comment]
Yes, this is my understading. "configuration as at the initial deployment".

**Comment by jvermillard** [comment]
FWIW we (Sierra Wireless) don't implement it this way, because rollbacking credentials can pose some security issues. We reset the device configuration but keep some info for not breaking the device. For example we keep cellular network config like APN for not disconnecting the device.
@boaks  I hope you don't brick your device because OMA required to do so in the spec :)

**Comment by boaks** [comment]
@jvermillard "your device", I miss millions of my devices :)

**Comment by jhorvath2017** [comment]
Thanks for your comments

Per the spec the expected behavior should be:
1)	Send 3/0/5 from Server to client to initiate factory reset
2)	Client sends deregister to remove device from server (OPTIONAL)
3)	Client performs reset 
4)	Client sends register to the server

Regarding the question about preserving any credentials or APN settings that would be assumed to be part of the factory condition and thus is not called out by the specification but left to the individual implementation. Similarly restoring the device to the “same configuration as at the initial deployment” is also implementation dependent. 

Per the existing spec:
Perform factory reset of the LwM2M Device to make the LwM2M Device to go through initial deployment sequence where provisioning and bootstrap sequence is performed. This requires client ensuring post factory reset to have minimal information to allow it to carry out one of the bootstrap methods specified in section 5.2.3.

When this Resource is executed, “De-register” operation MAY be sent (this is the optional Step 2 above) to the LwM2M Server(s) before factory reset of the LwM2M Device.

**Comment by nkaramolegos** [comment]
I have not understand when bootstrap take place? If my device reboot then it should bootstrap again? if not, bootstraping take place only in factory reset?

**Comment by giuseppe-melis** [comment]
@nkaramolegos I think the OMA spec is quite open to these items:
for example, in my commercial device and in most cases, the bootstrap is performed only during the first registration; the BS server provides the info for the DM server and the device/lwm2m client will recover them after each reboot.
Factory reset could reset (or not depending to your device logic) the lwm2m client info to the factory state as described in previous comments.
Which is your development?
Are you using an opensource lwm2m source or anything else?

**Comment by nkaramolegos** [comment]
> @nkaramolegos I think the OMA spec is quite open to these items:
> for example, in my commercial device and in most cases, the bootstrap is performed only during the first registration; the BS server provides the info for the DM server and the device/lwm2m client will recover them after each reboot.
> Factory reset could reset (or not depending to your device logic) the lwm2m client info to the factory state as described in previous comments.
> Which is your development?
> Are you using an opensource lwm2m source or anything else?

I am using leshan as lwm2m server. For the client I am using the implementation of contiki-ng

**Comment by sbernard31** [comment]
I guess the main bootstrap goal is to get enough data (like server url and credentials) to allow device to connect to 1 or several LWM2M server.

so simple scenario : 
 - device boot, it haven't any LWM2M server data, so it decide to bootstrap and get LWM2M server data, then it registers successfully to those severs. 
 - if this data  are persisted, it don't  need to do a bootstrap each reboot. (else it need)
 - now for some reason credentials change at server side (new X509 cert or PSK compromised), so device try to connect to server but it failed, so it need to re-bootstrap and so get new valid credentials. 
 
AFAIK, in LWM2M 1.0 there is no clear description about how device should decide to do a bootstrap. (it should find a good balance to not do a bootstrap at each failure)
In LWM2M 1.1, this is more specified ([§6.2.1.1 Bootstrap-and-LwM2M-Server-Registration-Mechanisms](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#6-2-1-1-0-6211-Bootstrap-and-LwM2M-Server-Registration-Mechanisms)) and even configurable using some [Server Object Resources](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#13-2-0-E2-LwM2M-Object-LwM2M-Server)

**Comment by fdur** [comment]
Hi @sbernard31 
maybe others use cases can be defined in order to connect again to the bootstrap server, like DM server address updates (the provided one on client side is no more available)
