### ISSUE TITLE
OMA-TS-LightweightM2M-V1_0-20161007-D, E 1.1.1, relation of key size and cipher suite

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#151]
> The PSK is a binary shared secret key between the Client and Server of the appropriate length for the Cipher Suite used [RFC4279]. 

Would it be possible to be more precise? Where in the RFC 4279 is a statement, that relates the size of the `preshared secret key` to the selected `cipher suite`? 
On my understanding, the provided `preshared secret key` is one part of the input to the `PRF` (TLS 1.2, RFC 5246, 5. HMAC and Pseudorandom Function) which generates the `cipher key`, which then MUST fullfill the requirements of the selected `cipher`. 

> This pseudorandom function (PRF) takes as input a secret, a seed, and
> an identifying label and produces an output of arbitrary length.

So, I can't see the hard relation of the `preshared secret key` size to the `cipher key` size.

"The default PSK Cipher Suites defined in this specification use a 128-bit AES key. Thus this key would be represented in 16 bytes in the Secret Key Resource."

As mentioned above, I can't see that hard relation!
The `cipher key` size is defined by the output of the `PRF`, the size of the `preshared secret key` is one part of the input of the `PRF` and therefore not hard related to `cipher key` size.

There may be a weak relation, say using a cipher with a blocksize of 128 has a "strength" which best matches a `preshared secret key` with 16 bytes. But it may be larger or smaller.

**Comment by hannestschofenig** [comment]
It is true that there is no requirement for the PSK to be exactly 128 bit long (for a ciphersuite that uses AES-128). Needless to say that reducing the length of the key will weaken security and hence the above should be seen as a recommendation instead. The key derivation function in TLS ensures that keying material is produced that fits the selected ciphersuite. In TLS 1.2 this means that a long key block is created, which is then chunked into parts for use with the two directions, IVs, etc. In plain TLS-PSK the security of the exchange really only depends on the length and the entropy of the PSK and nothing else. While the key derivation function will also mix in the random numbers exchanged in the ClientHello & ServerHello those are observable by the adversary since they are transmitted in clear over the wire. 

Note that the TLS PSK RFC does not recommend a specific size for the PSK either. I just found this publication, which may contain some useful information on this topic: https://eprint.iacr.org/2014/037.pdf
I haven't read it yet but will do.

**Comment by boaks** [comment]
Thanks for the fast response!

**Comment by hannestschofenig** [comment]
I created a CR with clarifying text for Appendix E.1.1.1, see    http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2016/OMA-DM-LightweightM2M-2016-0139-CR_psk_length.zip

Thanks for the feedback.

**Comment by boaks** [comment]
The proposed CR will fix my issue.

**Comment by boaks** [comment]
Sorry, I can't see, that OMA-TS-LightweightM2M-V1_0-20161007-D includes the CR!
Please wait for closing the issue until it's in the TS.

**Comment by boaks** [comment]
Fixed with OMA-TS-LightweightM2M-V1_0-20161123-D.
