### ISSUE TITLE
Issue with the U Binding Mode Concept due to NAT

### ISSUE THREAD

**Issue by gilbaruch77** [OpenMobileAlliance/OMA_LwM2M_for_Developers#169]
Usually clients have private IP address and located behind NATs.

When client initiate UDP communication with server, the connection maintained as long as client-server keep on communicating.

The point is that a while after the communication stops, the client wont be accessible by the server.

Usually clients solve that issue by using 'UDP hole punching' technique, however this method is not a good practice for IoT devices which should save battery power.

**Comment by hannestschofenig** [comment]
If the LWM2M client does not periodically send "keepalive" packets the NAT (or firewall) state expires and the server cannot reach out to the client anymore. This is not necessarily a limitation of LWM2M but rather a fundamental restriction of how the Internet works today. 

It turns out that there are actually two practical ways to reduce the described problems: 

1) You can use Queue Mode, which essentially changes the communication pattern in such a way that the client triggers the communication to subsequently let the server send requests. 

2) You can use CoAP over TCP since NATs and firewalls happen to choose their timeouts differently than for UDP traffic.

**Comment by hannestschofenig** [comment]
Here is a reference to a paper that describes the difference between the NAT binding lifetime difference for TCP and UDP: 
http://conferences.sigcomm.org/imc/2010/papers/p260.pdf

**Comment by gilbaruch77** [comment]
Currently TCP is not specified in the TS document.
Is it going to be standardized? (new binding mode?) 

Please consider standardizing client waking up by SMS similar to OMA-DM. This could be another way to overcome the described problem.

**Comment by dnav** [comment]
CoAP over TCP will be part of LwM2M 1.1.
Waking up by SMS is already part of LwM2M 1.0. Please see section 8.4 Update Trigger Mechanism
