### ISSUE TITLE
The use of endpoint names

### ISSUE THREAD

**Issue by hannestschofenig** [OpenMobileAlliance/OMA_LwM2M_for_Developers#180]
Name, version and date of the document: OMA-TS-LightweightM2M-V1_0-20161123-D
Section of the document: Section 5.2

The LWM2M specification describes how the bootstrap server provisions clients with the Security Object.
It is implicitly assumes that a certificate provisioned to the client (in the "Public Key or Identity" resource) contains the endpoint name since otherwise the security check, described in https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/175, fails. 

When a LWM2M client is configured to use multiple LWM2M servers then the bootstrap server has to provision multiple Security Objects, which contain multiple client certificates. In some deployment environments it may be acceptable to use the same client certificate in all Security Objects but in other environments privacy requirements may dictate that the client uses different certificates. If that's the case, then the client also needs to use an endpoint name that matches the content of the certificate. Since there is no separate resource that lists the endpoint name it has to use with a given LWM2M server it needs to parse the certificate first and then use that identifier as an endpoint name.

I would therefore suggest to discuss this topic explicitly and to point out that this leads to improved privacy properties, which may be important in some environments.

**Comment by boaks** [comment]
Indeed, the generated certificates (x509) must obey the rules in OMA-TS-LightweightM2M-V1_0-20161123-D, Section 7.1.3. "A LWM2M Client Certificate MUST include the Endpoint Name parameter used to register the device in the Subject Common Name (CN) field of the Certificate."
Otherwise, the security check defined there will not work.

But, knowing the "endpoint name", why shouldn't the bootstart server (or the CA used) be able to generate a proper certificate with that name in CN? The certificate should then contain the information about the different server in the other parts of the DN (e.g. O or OU). So what is your assumed process, which may not be able to generate proper certificates? Do you consider the endpoint name being unknown? Or what do I miss? Why should someone be forced to generate certificates without the endpoint name in CN?

**Comment by hannestschofenig** [comment]
I would like to point out that there is a privacy consideration here that is not described in the text. If a LWM2M client uses multiple LWM2M servers then it may be wise to generate different certificates for the LWM2M client for the use with these servers so that correlation is not possible.

**Comment by boaks** [comment]
> I would like to point out that **there is a privacy consideration** here that is not described in the text. If a LWM2M client uses multiple LWM2M servers then it may be wise to generate different certificates for the LWM2M client for the use with these servers so **that correlation is not possible**.

Now I think, I start to understand: 
You **want** to provide client certificate in a way, **that correlation is not possible**. Right?

**Comment by aschen77** [comment]
OMA-TS-LightweightM2M-V1_0-20170208-A seems to have relaxed the requirement of the endpoint name having to match the Subject Common Name in the client certificate. Instead it just refers to the "identifier" of the certificate which is ambiguous. Does this mean the implementation can decide the unique mapping from client certificate fields to endpoint name?

**Comment by hannestschofenig** [comment]
Text was added in LwM2M v1.0 to speak about the privacy implications of re-using credentials with multiple LWM2M servers.
