### ISSUE TITLE
Access Control when changing the set of existing LWM2M Server Accounts

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#183]
The description below is based on the current draft 1.0 version of the LWM2M specification (OMA-TS-LightweightM2M-V1_0-20161222-D).

## Description

Section E.3.1 (Object Instance Configurations) states that:

> If a new LWM2M Server Account is added when LWM2M Client has only one LWM2M Server Account, Client MUST ensure that Access Control Object Instances for every Object Instance except Security Object Instance exist. The LWM2M Client MUST create the missing Access Control Object Instances as follows:
> * Access Control Owner MUST be the previously existing LWM2M Server
> * Previously existing LWM2M Server MUST have full access right.

Knowing that an "LWM2M Server Account" is defined in section 3.2 (Definitions) as "LWM2M Security Object Instance with Bootstrap-Server Resource false and associated LWM2M Server Object Instance", it is easy to see that the only way in which an LWM2M Server Account may be added, is via the Bootstrap Interface - either through communication with an LWM2M Bootstrap Server, or through e.g. Bootstrap from Smartcard (as section 5.2.3.2 Bootstrap from Smartcard states that the Client needs to regularly check for changes in the smartcard-provisioned configuration). Only the Bootstrap Interface provides a way to create an LWM2M Security Object Instance, which is an integral part of the LWM2M Server Account.

In this light, the statement from section 7.3.1.1 (Access Control Object overview):

> Access Control Object MUST be instantiated with the following rules:
> * During the Bootstrap Phase, an Access Control Object Instance MUST be assigned per Object, for identifying which Server will be authorized to instantiate this Object later. The Bootstrap-Server is the owner of these Access Control Object Instances created during this phase.
> * (...)

seems to be in direct contradiction with the previously quoted section E.3.1. This requirement is also reinstated in section 7.3.1.2.1 (Access Control Object Instantiation). Section 7.3.1 requires all Access Control Object Instances instantiated automatically during the bootstrap phase to be owned by the Bootstrap Server (owner=65535), while section E.3.1 requires the specific case of adding more Server Accounts to a Client that already has exactly one, to produce Access Control Object Instances owned by the pre-existing server.

Moreover, assuming that the case described in section E.3.1 is a specific case that takes precedence only when it is applicable, it is very non-trivial to decide when it may be applicable and when not, as illustrated in the following examples.

## Motivating example

Imagine an LWM2M Client containing the following objects:
* /0 (Security)
  * /0/0 - Bootstrap Server account; exact contents irrelevant
  * /0/1
    * /0/1/0 (URI): `coaps://1.2.3.4:1234`
    * /0/1/1 (Bootstrap): `false`
    * /0/1/2 (Security mode): `0` (PSK)
    * /0/1/3 (PK/Identity): `identity1`
    * /0/1/4 (Server PK): (empty)
    * /0/1/5 (Secret Key): `<KEY1>`
    * /0/1/10 (SSID): `1`
* /1 (Server)
  * /1/1
    * /1/1/0 (SSID): `1`
    * /1/1/1 (Lifetime): `86400`
    * /1/1/6 (Notification Storing): `false`
    * /1/1/7 (Binding): `U`
* /2 (Access Control)
  * no instances - as described in 7.3 (Access Control), "(...) where a single LWM2M Server Account exists (...) the Access Control Object MAY be not instantiated" (*)
* (some more Objects, containing some useful resources)

(*) - there is an additional slight discrepancy here - does "Object not instantiated" mean "no object in the data model" (not even `</2>` reported by Discover) or "object with no instances"?

### Example scenario 1

The Bootstrap Server executes the following series of commands:

* BOOTSTRAP DELETE /0/1
* BOOTSTRAP DELETE /1/1
* BOOTSTRAP WRITE /0:
  * /0/1:
    * /0/1/0 (URI): `coaps://1.2.3.4:1234`
    * /0/1/1 (Bootstrap): `false`
    * /0/1/2 (Security mode): `0` (PSK)
    * /0/1/3 (PK/Identity): `identity1`
    * /0/1/4 (Server PK): (empty)
    * /0/1/5 (Secret Key): `<KEY1>`
    * /0/1/10 (SSID): `1`
  * /0/2:
    * /0/2/0 (URI): `coap://5.6.7.8:5678`
    * /0/2/1 (Bootstrap): `false`
    * /0/2/2 (Security mode): `3` (NoSec)
    * /0/2/3 (PK/Identity): (empty)
    * /0/2/4 (Server PK): (empty)
    * /0/2/5 (Secret Key): (empty)
    * /0/2/10 (SSID): `2`
* BOOTSTRAP WRITE /1:
  * /1/1:
    * /1/1/0 (SSID): `1`
    * /1/1/1 (Lifetime): `86400`
    * /1/1/6 (Notification Storing): `false`
    * /1/1/7 (Binding): `U`
  * /1/2:
    * /1/1/0 (SSID): `2`
    * /1/1/1 (Lifetime): `86400`
    * /1/1/6 (Notification Storing): `false`
    * /1/1/7 (Binding): `U`
* BOOTSTRAP FINISH

In this example, the old SSID=1 LWM2M Server Account has been deleted, but an exactly identical Account has been created in its place. Is it "the same Server Account" (as it is indistinguishable) or not (as there was a Delete operation earlier)? As such, should the missing Access Control instances be populated according to rules of section E.3.1 (giving full access to server SSID=1), or according to rules of section 7.3.1 (owned by Bootstrap Server and giving no access to either of servers)?

### Example scenario 2

* BOOTSTRAP WRITE /0: (contents as in example scenario 1)
* BOOTSTRAP WRITE /1: (contents as in example scenario 1)
* BOOTSTRAP FINISH

There is no Delete operation, but the /0/1 and /1/1 object instances are rewritten - with exactly the same data that was present in them before. Is it "the same Server Account" now or not? Which rules of Access Control instantiation apply?

### Example scenario 3

* BOOTSTRAP WRITE /0:
  * /0/1:
    * /0/1/0 (URI): `coaps://4.3.2.1:4321`
    * /0/1/1 (Bootstrap): `false`
    * /0/1/2 (Security mode): `0` (PSK)
    * /0/1/3 (PK/Identity): `identity2`
    * /0/1/4 (Server PK): (empty)
    * /0/1/5 (Secret Key): `<KEY2>`
    * /0/1/10 (SSID): `1`
  * /0/2: (contents as in example scenario 1)
* BOOTSTRAP WRITE /1/2: (contents as in example scenario 1 for instance /1/2)
* BOOTSTRAP FINISH

In this scenario, the Instance IDs and SSID of the pre-existing Server Account remain unchanged, but the URL and security keys of it are replaced. Is it "the same Server Account" now or not? Which rules of Access Control instantiation apply?

### Example scenario 4

* BOOTSTRAP WRITE /0:
  * /0/2: (contents as in example scenario 1)
* BOOTSTRAP WRITE /1/1/6 (Notification Storing): `true`
* BOOTSTRAP WRITE /1/2: (contents as in example scenario 1 for instance /1/2)
* BOOTSTRAP FINISH

Here, a new server is created almost without touching the pre-existing Sever Account, but a minor parameter of the pre-existing Server Account (Notification Storing) is modified. Is it "the same Server Account" now or not? Which rules of Access Control instantiation apply?

### Example scenario 5

* BOOTSTRAP DELETE /0/1
* BOOTSTRAP DELETE /1/1
* BOOTSTRAP WRITE /0:
  * /0/2: (contents as in example scenario 1)
  * /0/42:
    * /0/1/0 (URI): `coaps://1.2.3.4:1234`
    * /0/1/1 (Bootstrap): `false`
    * /0/1/2 (Security mode): `0` (PSK)
    * /0/1/3 (PK/Identity): `identity1`
    * /0/1/4 (Server PK): (empty)
    * /0/1/5 (Secret Key): `<KEY1>`
    * /0/1/10 (SSID): `1`
* BOOTSTRAP WRITE /1:
  * /1/2: (contents as in example scenario 1)
  * /1/69:
    * /1/1/0 (SSID): `1`
    * /1/1/1 (Lifetime): `86400`
    * /1/1/6 (Notification Storing): `false`
    * /1/1/7 (Binding): `U`
* BOOTSTRAP FINISH

In this example, the pre-existing Server Account "moves" to different Security and Server Object Instances, with different IDs, but all other values of the Server Account remain unchanged. Is it "the same Server Account" now or not? Which rules of Access Control instantiation apply?

## Summary

Obviously, even more examples can be created. The main concern here is: how is the "previously existing LWM2M Server" identified? By Security Instance ID? Server Instance ID? Short Server ID? A tuple of those three? All or some part of the resources in the relevant Security and/or Server Instances? Does a Bootstrap Delete operation automatically invalidate the relevant Server Account, even when an identical one is re-created afterwards? What about Bootstrap Write on existing Security and/or Server Instances?

I personally think that the rules described in section E.3.1 are somewhat vague and should be abandoned completely - the Bootstrap Server may create Access Control object instances for the pre-existing server as necessary. Attempting to automate this process on the client side leads to vagueness and may lead to unexpected results - slight differences in interpretation of the spec may lead to Bootstrap Server expecting different contents of the Access Control object than the Client actually instantiates.

**Comment by dnav** [comment]
Hi,

Thank you for this very detailled issue. We will improvw the Access Control mechanism.

Regards,

**Comment by ThGarnier** [comment]
Hi kFYatek
First of all, many thanks for your detailed and clear questions.  I will try to show you there is no contradiction (at least on the essential part) between the section E.3.1 and section 7.3.1.1 (in fact 7.3.1.2.1) ; however you are right, to the light of your comments, the TS in section E.3 and Section 7.3 must be slightly amended to remove ambiguities, to add clarification but also to lighten the Client job; this simplification is now possible (according to your suggestion in Summary) because of the new DISCOVER command features. Previously only the Client has enough information to switch a Device (already configured with a list of Objects Instances) from a Single Server context, to a Multiple-Servers context (so to create a-posteriori Access Control Object Instances containing the proper values). 
Sorry, I will not answer to all yr questions here, however I hope providing you enough information to clarify essentials points.
More and less implicit (at least explicitly said in E.1.3): a Security Object Instance has no associated Access Control Object Instance; only the Bootstrap Server can access to it.
To my view there is no contradiction (just I agree, it is particularly unclear ) between E.3.1 & 7.3.1.1  because they address 2 different cases. 
E.3.1 addresses the case a configuration (list of Instantiated Objects) is in place in a Device running in a Single Server Context. When switching to a  Multi Server Context, the proper Access Control Object Instances –which were initially not present - must be created  for each Object Instance and Object of the initial configuration (in current spec the Client is in charge of such creations, ‘cause only the Client has the proper knowlegde   - e.g. ssid); with introduction of the Bootstrap Discover command, the Bootstrap-Server should take this job in charge.
The part of the Section 7.3.1.1 you are mentioning (in fact the 7.3.1.2.1 Bootstrap case), is a  nominal case in the Multiple Server Context : the Access Control Object Instances  - owned by the Bootstrap-Server -, are Instances which must specify  for a particular Object, which LwM2M Server(s) is(are) able to create  an Instance of such a particular Object (ACL with ssid as index, and ‘C’ as access right – ACL value) .  In Bootstrap case, what is currently missing is to say that other Access Control Object Instances could be created (or updated) to set  the access rights (e.g. ‘RW’ as ACL value) of a LwM2M Server (ssid as ACL Index) for a certain Object Instance (with the same final result of the 7.3.1.2.1 “Create” operation case performed by a LwM2M Server)  
Hope it  is clearer now, regarding that part.  The TS will be clarified soon. 
Thierry

**Comment by kFYatek** [comment]
Hi Thierry,

Thank you for your reply. Well, the purpose of those sections was clear to me from the start, and yes, what you described here can be pretty much implicitly guessed from what is said in both E.3.1 and 7.3.1 sections.

However, what is unclear is: _what constitutes the "previously existing LWM2M Server" when switching from Single Server to Multi Server Context?_

* If a Bootstrap Server performs a BOOTSTRAP DELETE / (all instances of all objects) operation and then creates the whole data model (with multiple servers) from scratch, it is rather clear that the intent is to start anew - it's getting rid of any "previously existing server", if any, so the Client shall use the 7.3.1 rules and give the Bootstrap Server full ownership of all initial ACLs.
* If a Bootstrap Server just calls BOOTSTRAP WRITE with a new instances of the Security and Server object, adding a new Server Account in addition to pre-existing ones, then it is clear that the intent is to switch from Single Server to Multiple Server Context, and rules described in E.3.1 are applicable.

However, between the two clear cases above there is a broad gray area, illustrated by the examples in my original post. What if the server overwrites resources in a pre-existing Server Account without previously deleting it? Is it the same "previously existing LWM2M Server" or a new one? What about deleting and then recreating an identical one?

While it is unlikely that such scenarios may make any sense from the Bootstrap Server's perspective to actually perform, the Client must have clear algorithms on how to behave in such circumstances, but the proper way of implementation is not clear (at least to me) from the current spec revision.

**Comment by ThGarnier** [comment]
Hi kFYatek
As mentioned in my previous partial answer, due to the fact the Bootstrap Server has now much more investigation power with Discover Command, the switch from single to multiple Server context, can (and so must)be fully taken in charge by a Bootstrap Phase; so E.3.1 requirement doesn’t imply the Client any more (in fact this paragraph is removed in the current proposal); The Bootstrap Phase is in charge of preparing a consistent multi-server configuration 
According  to yr 1st bullet, the only wrong point is that the Bootstrap Server has not the ownership of all initial Access Control Object Instances (even if it can write or delete them). It seems ( sorry the spec was no so clear on it so on-going proposal changed it I hope  ) there is a misunderstanding on the fact there are  : a) Access Control Object Instances (owned by the Bootstrap Server) on Objects for authorizing certain LwM2M Servers to create Object Instances, and  b) Access Control Object Instances determining which LwM2M Server (defined as owner) able to grant access rights to other LwM2M Servers for a certain Object Instance.
So as a general rule don’t be worry about E.3.1 or 7.3.1 rule; the only things is :”after a Bootstrap Phase”, if a Multi-Server context has been setup, it must be consistent (Access Control Object Instances setup by the Bootstrap Server must reflect the need).
To simply answer your question : if you are deleting and recreating a server account identically before sending the Bootstrap Finish, nothing happens. 
According to all your examples, in fact the results will be the same  for all (except if I miss one point); as all your configurations contain no Access Control Object Instances, but only 2 LwM2M Servers Account (Abstraction of the Bootstrap Server account) and certainly other lwM2M Object Instances, the first request of any of yr LwM2M Server will receive an “Access Right Permission Denied”  (7.3.2.1) .
I really hope the restructured text for the Access Control part of the spec 7.3 will be available soon to discuss more concretely. However hope my comments helps you to clarify the view :-)
Thierry

**Comment by ThGarnier** [comment]
If my explanation are clear and acceptable enough,  could we close this current issue, and possibly reopen a new one on fresh basis when the new text will be available according to the principles provided above ?
Th

**Comment by kFYatek** [comment]
Yes, I think it's OK. Thank you :)

**Comment by ThGarnier** [comment]
good :-)

**Comment by Megan-OMA** [comment]
Issue closed per comments / agreement above.
