### ISSUE TITLE
Instantiation of Access Control Object instances

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#192]
The description below is based on the current draft 1.0 version of the LWM2M specification (OMA-TS-LightweightM2M-V1_0-20170208-D).

Hello again ;) We previously resolved an [issue with Access Control](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/183) that placed an unnecessary burden on the Client devices regarding switching from Single to Multiple server environment. But I feel that the overall Access Control wording is still far from clear.

Sections 7.3.1.2.1 (Access Control on Object) and 7.3.1.2.2 (Access Control on Object Instance) say the Access Control Object Instances **MUST** be associated for each Object and Object instance present in the data model. They also say that they shall be initially created during the Bootstrap Phase - however, they don't seem to explicitly say whose responsibility it is to ensure that.

In particular (let's assume we're dealing only with Multiple Server environments for now):
- When a Bootstrap Server sends the BOOTSTRAP FINISH command while some Access Control Object Instances are missing (i.e. they are not instantiated for each supported Object or for each present Object Instance), what should the Client do?
  - Respond to the BOOTSTRAP FINISH command with an error?
  - Create the missing Access Control Object instances itself (setting Owner to 65535) and finish the Bootstrap Phase successfully?
  - Finish the Bootstrap Phase successfully without creating the missing instances? (this would seemingly contradict with the "MUST" keywords used in 7.3.1.2)
- How should the Client behave during a Bootstrap from Smartcard, if the bootstrap data file (as described in section G.3.3) does not contain Access Control Object instances for all the Objects and Instances mentioned within it?

Similar questions can be raised for automatic removal of Access Control Object instances. Should the Client remove ACO instances that are no longer valid (e.g. refer to non-existent Objects or Servers) at the time of BOOTSTRAP FINISH? Or should they be left "lingering"? (that would seemingly be somewhat inconsistent with E.1.3 Unbootstrapping)

**Comment by ThGarnier** [comment]
I agree, specifying an access control functionality is never easy, whatever the spec, and LwM2M has still to improve that section for sure.
However, maybe  I can help you  -hope so :-) - to clarify the picture especially when wording introduced  some ambiguity.
First : it will help to really separate 7.3.1.2.1 & 7.3.1.2.2 and not setting them in the same pot (even if wording seems quite similar) as you do.
Second : The spirit is : for addressing a certain functionality (7.3.1.2.1, 7.3.1.2.2 ) an association with an AC Object Instance must be performed (if not performed, functionality is not achievable) : so at least, you are right,  the text is ambiguous.  
In 7.3.1.2.1 (AC Object Instance on Object) : The first sentence should be reversed a bit to better address the spirit : "In order to specify if an Object supported by the LwM2M Client can be instantiated ("Create" operation) by a LwM2M Server, an Access Control Object Instance MUST be associated to such an Object. This kind of  Access Control Object Instance MUST have its Resource set as given in the table just below" .
For me this should remove the ambiguity.
In the same section, the first bullet is more delicate to answer : In fact, creating this association (as said in the TS), doesn't solve any issue  if the ACL resources are not present (since in that case no Server will able to create one Instance on such an orphan Object): so for me, but I agree it is not in the spec - and so this has to be discussed/fixed in OMA DM WG- the sentence should be inline with the spirit in saying : If such association doesn't exist , no LwM2M Server will be able to create an Instance for that Object.  

Section 7.3.1.2.2  (AC Object Instance on Object Instance): again the sentence should be reversed to match the spirit better:
"In order to specify which operations MAY be performed by a certain LwM2M Server on a certain Object Instance, such an Object Instance MUST be associated to an Access Control Object Instance". 

So comes your particular questions : 
. If missing AC Object Instances doesn't break any inconsistency, BOOTSTRAP-FINISH must not report an error (not being able to create  Object Instances is not an inconsistency by itself) 
. again the 1st bullet of 7.3.1.2.1 must be discussed and fixed (OMA DM WG) but IMHO, automatically creating this empty AC Object Instances (no ACL resource) doesn't help : so for me no creation
.  so finish the Bootstrap Phase successfully without creating the missing instances (in accordance with the 1st bullet)    : for me yes  (but need official confirmation by OMA WG decision)

. with smartCard bootstrap : the same behavior: if there is no inconsistency, the Bootstrap configuation is validated; if there is any inconsistency the Client remains on its previous Bootstrap Information.
As said just above, missing AC Object Instances should be not - in itself - a cause of inconsistency 

Regarding the orphan AC Object Instances,  you are right,  nothing is specified. Not sure to impose this TS could be  good; certainly it could be let implementation dependant. In LwM2M 1.1, the Boostrap Server should have better view on this, and could safely decide to take the responsability to remove
"lingering" ACO Instances.

Hope my reply clarified the picture a bit, even I cannot have, all the definitive answers yet; TS will be clarified  (still to define under which form)
 Thanks for your pertinent questions :-) 
Thierry

**Comment by jpradocueva** [comment]
Agreed with DM Working Group to close.
