### ISSUE TITLE
Same or separate DTLS sessions for Register and Object access.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LwM2M_for_Developers#2]
Register    

```
   CLIENT  --> DTLS Client Hello --> SERVER
                   <--      SERVER Hello  <--
                  -->        …                     -->
```

CoAP indicates that a new session is needed for the following command READ

```
   CLIENT    <-- DTLS  Client Hello    <--
                    -->     Server Hello         -->
                   <--         …                       <--
```

It is not clear in the specifications.

**Comment by mkovatsc** [comment]
In CoAPS, an endpoint is identified per source address, port, and security context. Since the Object access (Read, Write, etc.) is supposed to be done on the endpoint that registered, you MUST use the same DTLS session. This should be repeated clearly in the LWM2M TS.

Another question is if the LWM2M Server can initiate a new session as DTLS client. For that the LWM2M Client has to implement DTLS server role. This is not clearly defined in the TS. The IETF DICE Profile initially assumed DTLS client role only on LWM2M Clients; the savings of omitting server role are marginal and server role is used for other scenarios.
Option 1: The LWM2M could make DTLS server role optional  for LWM2M Clients and LWM2M Servers then have to wait for a Client Registration (Update).
Option 2: Make both DTLS client and server role mandatory. This might not be required for some use cases and then wastes memory.

**Comment by mkovatsc** [comment]
The TS should also specify the behavior for UDP+SMS modes. Here, there will be two sessions, one over UDP, one over SMS. Technically, the Server is then talking to two different endpoints, but the Client can correlate the sessions through the `LWM2M Server SMS Number` in the Security Object.

Note that DTLS over SMS is not fully figured out yet...

**Comment by BillBennett** [comment]
There is also an interaction with Queue Mode and NAT:
Presumably when the client is using UQ mode with security, the first registration update or observe notification after a period of sleep should use a DTLS session resumption, otherwise decryption will fail if the port mapping changes.
Is that enough for notifications to work?

**Comment by mkovatsc** [comment]
The observe draft says "All notifications resulting from a GET request with an Observe Option MUST be returned within the same epoch of the same connection as the request."

A session resumption, however, results in a new epoch (at least to my understand; could not find a clear statement in the specs do far). That means all observe relationships must be re-enabled (GET with same token) after a port change. Ideally, pmax is set just below the NAT timeout for UDP...

This is why NAT is hazardous for the IoT. Currently, the best solution is to use the upcoming TCP/TLS binding for CoAP. In the long-run, we probably revisit the problem during the adoption of DTLS 1.3.

I think when NAT and IPv4 is involved, we are actually not dealing with constrained environments and their is no resource constraint argument for the LWM2M client. That is also why the TCP binding makes sense in the first place.

**Comment by BillBennett** [comment]
OK so Observe still doesn't work. Is my assumption still valid for the registration update?

**Comment by jvermillard** [comment]
If a client in queue mode behind a NAT, resume the DTLS session successfully, why it would be a problem to send a notification to the server for an observe issued during the "registration" ? The server will just correlate the notify with the observe request using the token and the DTLS session.

I don't understand why in the observe draft they are restricting to the same epoch number. 
Anyway I think notifying over a new DTLS session resume or a new TLS/TCP connection but for the same registration would be useful (the device can sleep) and is implementable.

**Comment by mkovatsc** [comment]
This is a conservative decision in the spec to avoid a possible thread through a known cross-epoch attack.

There is already the idea for "Unsolicited Notifications" that could solve the problem. It will be different spec, though, and will require support from security guys to check the possible security holes.

Best raise this topic on the mailing list and include the author directly (hartke@tzi.org).

**Comment by jvermillard** [comment]
thanks for the details Matthias!

**Comment by hannestschofenig** [comment]
I guess it would be a good idea to bring the CoAP/epoch topic up at IETF#100 since the DTLS Connection ID work has been agreed in the TLS WG.

**Comment by hannestschofenig** [comment]
The original question by Joaquin has long been answered. The subsequently raised questions are not related to the original question.
