### ISSUE TITLE
Clarify Reusable Resource

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#205]
OMA-TS-LightweightM2M-V1_0-20170208-A, D.2.2 Resource Registry

> Reusable Resource ID range – Registered by an Object Specification, with the Resource ID assigned by OMNA. Defined in any Object specification. Resources from this Resource ID range can be re-used in any Object.

Please clarify, how this "re-used" should work:
"explicit at the object definition" (resources **MUST** be listed in the objects definition)
"implicit by just using it" (reusable resource could be always optional included in a object without listing the usage in the object definition)

The question may require to be discussed with the IPSO idea. 

https://github.com/IPSO-Alliance/pub/issues/6

> However, since they are both Optional Resources, you can add min-max, it should not be a problem.

The answer implies for me the idea, that reusable resources could just be reused without explicitly declaring the usage in the object definition. But I'm not sure, if this is really intended.

**Comment by hannestschofenig** [comment]
You are correct that there should be a section that talks about how we expect LwM2M to be extended and the use of reusable resources fits into that model. In the IETF we have written a number such documents for protocol. Here is an example from Diameter: https://tools.ietf.org/html/rfc7423

**Comment by ThGarnier** [comment]
In LwM2M 1.0 (1.0.1) there is no concept of "implicite" or "explicite" resource : the Resource of an Object  can be either Mandatory or Optional; that's all 
So when an Object is defined any included Resource  (whatever it is reusable or not) must be specified if it is Mandatory or not, multi-Instance or not ..
The re-usable resource has an ID which is publicly registered at OMNA, and a set predefined characteristics (datatype, capability...), but otherwise it has to be handled as any other Resource when it is part of an Object definition.
Thierry

**Comment by boaks** [comment]
@ThGarnier 

Thanks! This was also my understanding. 

@jaimejim 

https://github.com/IPSO-Alliance/pub/issues/6

If a "reuseable resources" must be declared **explicitly** to be used by an object, I can't add the "min-max range" on my own, because this changes the OMA registered object definition.

**Comment by jaimejim** [comment]
@boaks 
Originally with reusable resources was to have them in order to device vendors to build Objects that were not available in the OMNA registry. How that Object would be shared was out of the scope of the group. I'd understand it as option two: "implicit by just using it".

As @ThGarnier pointed out reusable resources have a specific unique identifier. LWM2M resources do not have that at the moment. 

We could extend the spec and clarify that.

**Comment by boaks** [comment]
I'm just wondering:
For OMA it'st "explicit" and for IPSO "implicit".
So, FMPOV, currently it just doesn't work :-).

**Comment by jaimejim** [comment]
@boaks both organisations have now merged, so we can figure out how to update the object definitions. 
I'f prefer to have the possibility to have reusable resources instead of having explicit definitions only. If reusability is not contemplated Resource IDs have little sense then, as they have meaning only within an existing object.
