### ISSUE TITLE
Update IPSO object definitions

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#212]
Some IPSO objects in

https://github.com/IPSO-Alliance/pub/tree/master/reg/xml

have been updated/fixed. Would it be possible, to update the related definitions in

http://www.openmobilealliance.org/tech/profiles/lwm2m

also?

**Comment by jpradocueva** [comment]
OMA LwM2M v1.0 has introduced the concept of Object versioning.
I believe that the new changes should be reflected under a new object version, e.g. v1.1.
This topic needs to be discussed between IPSO and OMA.

**Comment by boaks** [comment]
Just to say: 

With the old definitions (some objects defines the resource "unit" accidentally as "float" instead of "string"), I'm not sure, who's able to use them :-).

If the OMA starts to discuss with IPSO, could you also please clarify the issue #205 ?

**Comment by jpradocueva** [comment]
Thanks for adding issue #205
This may take some time to resolve as the person to deal with this in IPSO is not available right now.

**Comment by jaimejim** [comment]
Hi all, 
for IPSO related issues I'd be happy to help. Perhaps you can add me to the "Assignees" next time?
Also for those related to IETF drafts for that matter, perhaps I can be of assistance.

**Comment by jpradocueva** [comment]
IPSO Alliance has merged into OMA. 
The resolution of this issue will be part of the discussions on how to integrate IPSO in OMA.

**Comment by jaimejim** [comment]
@boaks @hannestschofenig  as far as I'm concerned the issue of floats/strings was fixed back in May 2017, the units have been string since then. I think OMA should just merge the latest objects in: https://github.com/IPSO-Alliance/pub/blob/master/reg/xml 

Regarding versioning, we didn't use it in IPSO and OMA has not yet have a discussion about that. I think that should be a different issue.
