### ISSUE TITLE
Provisioning of keys using Raw Public Keys mode

### ISSUE THREAD

**Issue by moleike** [OpenMobileAlliance/OMA_LwM2M_for_Developers#220]
* OMA-TS-LightweightM2M-V1_0_1-20170704-A
* Section 7.1.8 Raw Public Keys
* Bootstrap server securely (using RPK mode) writes a Security Object.

Q: Both Bootstrap and LWM2M server X use RPK. Does the client need a distinct client key-pair for each server, or can it be shared? If it can be shared, can the Bootstrap server omit writing the client key-pair in the security object for sever X?

/cc @hannestschofenig

**Comment by jpradocueva** [comment]
@moleike  please note that the latest TS can be found here: http://www.openmobilealliance.org/release/LightweightM2M/ 
Currently, the latest TS is V1.0.1 dated on 2017 07 04 - A. Future releases will also appear in this page.

**Comment by moleike** [comment]
@jpradocueva updated, thanks.

**Comment by hannestschofenig** [comment]
Hi @moleike 

In Section 7.1.2 of http://www.openmobilealliance.org/release/LightweightM2M/V1_0-20170208-A/OMA-TS-LightweightM2M-V1_0-20170208-A.pdf we talk about this aspect: 
"
LwM2M Bootstrap-Servers, LwM2M Servers and LwM2M Clients MUST use different key pairs. LwM2M Clients MUST use keys, which are unique to each LwM2M Client. When a LwM2M Client is configured to utilize multiple LwM2M Servers then the LwM2M Bootstrap-Server may configure different credentials with these LwM2Ms Servers. Such configuration provides better unlinkability properties since each individual LwM2M Server cannot correlate request based on the credentials used by the LwM2M Client. Deployment and application specific considerations dictate what approach to use.
"

Hence, you can use a single RPK on the LwM2M client for use with multiple LwM2M servers but you will loose the unlinkability property. You need to investigate whether this is a concern in your deployment. 

The LwM2M client cannot, based on our recommendation, share the same key pair with the bootstrap server and with one or multiple LwM2M servers. 
The reason is somewhat simple: we don't have a mechanism in LwM2M to change the keying material for use with the bootstrap server since it acts as the "root of trust". If it is the same as the credential being used with the LwM2M server(s) then this would not be possible to change either. 

Regarding your question whether there is an optimization used where the bootstrap server only writes a single key and that key gets used multiple times by various LwM2M servers. The answer is "no", there is no such optimization incorporated right now. However, given that LwM2M clients typically have a limited number of LwM2M servers they talk to (often just one) this optimization does not appear to be very important. 

Does this answer your question?

**Comment by moleike** [comment]
@hannestschofenig indeed, concise and clear, thanks.
