### ISSUE TITLE
http://openmobilealliance.org/tech/profiles/LWM2M.xsd: Use xs:all instead of xs:sequence

### ISSUE THREAD

**Issue by davidgraeff** [OpenMobileAlliance/OMA_LwM2M_for_Developers#221]
At the moment the XML Schema file reads like this:
```
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="LWM2M">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="Object">
          <xs:complexType>
            <xs:sequence>
```

I suggest to change from `sequence` to `all`, otherwise some of the OMA LwM2M Registry xml files will not validate, because they have Description1 and Description2 grouped together instead of following the order defined in the schema file.

The suggested change would read like this:
```
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="LWM2M">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="Object">
          <xs:complexType>
            <xs:all>
```

**Comment by jpradocueva** [comment]
Also thanks for this David. We will review it within the team.

**Comment by davidgraeff** [comment]
Any progress on fixing the schema file?

**Comment by jpradocueva** [comment]
We are doing the final checks, then the Device Management Working Group needs to agree the changes against the schema. This topic will be reviewed at the next face to face meeting 12-14th Sep.

**Comment by jpradocueva** [comment]
At the end DM agreed to keep the same schema.
All the documents in the OMNA registry were reviewed. 
The following files failed validation due to a problems with the order of some fields:
    10245.xml
    10246.xml
    10247.xml
    10248.xml
    10249.xml
These documents were rectified and a license were included.
All the new registrations will be validated even if they have been submitted by the tool.

If the DM working group decides to update the schema for lwm2m v1.1, then we will introduce the suggested change from ```sequence``` to ```all```.
