### ISSUE TITLE
Common.xml: Schema violation regarding "MultipleInstances" field

### ISSUE THREAD

**Issue by davidgraeff** [OpenMobileAlliance/OMA_LwM2M_for_Developers#222]
The xml file that describes the common resources does not validate with the given XML Schema. Multiple resources (I counted 55) have no value set for `<MultipleInstances>`, which according to the Schema must be Single/Multiple.
It might be an idea, to change the schema and semantic instead and assume a default value of "Single".

**Comment by jpradocueva** [comment]
Thank David, we will look into this.

**Comment by jpradocueva** [comment]
Working Group needs to confirm the the of  `<MultipleInstances>` (Single or Multiple) for Reusable Resource 4000 as currently it is empty.

**Comment by davidgraeff** [comment]
I just noticed this is just the first out of many Schema violations regarding <MultiInstance>, I counted 55 uses of `<MultipleInstances />` (no value assigned). It might be an idea, to change the schema and semantic instead and assume a default value of "Optional".

**Comment by jpradocueva** [comment]
@davidgraeff we have looked to this issue and the resolution is complicated.

The DDF.xml and the Common.xml files were never intended to be used beyond a storage of the LwM2M Registry and LwM2M editor tool, therefore we didn't consider the validation of either of these documents. 

Common.xsd file was produced as storage of the reusable resources no as an Object itself.  In OMNA Reusable Resources are registered and defined separately but the registration only request the following fields: 
* Name
* Operations
* Type
* Range or Enumeration
* Units
* Description
but "Mandatory" and "MultipleInstances" fields are **NOT** required as part of the registration of the Reusable Resource registration. However,these fields MUST have a value in the definition of an Object. This is the reason why most of the resources inside of Common doesn't have any values on these fields.

In addition since the creation of the Common.xml file, the working group decided to extend the Reusable Resources with the addition of the name of the "Submitter"; this field doesn't exist in the LwM2M Schema but it is required in the Common.xml to display in the web page. All in all, Common.xml will never validate correctly against the schema for all these reasons.

The working group is currently discussing the addition of labels to the registry in order to classify Objects and Resources. This will imply a further enhancement of the Common.xml and DDF.xml files. Which cannot be easily accommodate.
Therefore, we are considering to move the content of the LwM2M Registry to a database and facilitate a API service to access Objects and Resources.
Is this something that you will welcome? If yes, I would like to hear your use case to ensure that the new database and API address your needs.
Thanks

**Comment by davidgraeff** [comment]
The storage actually doesn't matter to me (file or rest service). But the service will return a json or XML again. The format of the response should be documented machine readable and validatable if possible.
