### ISSUE TITLE
Test Cases Issues - Warsaw

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LwM2M_for_Developers#236]
ETS: OMA-ETS-LightweightM2M-V1_0_1-20170830-D

* [ ] **Test Case 303**
  * 303 test case implies Observe on the object not at the resource level in order to Observe Cancel 

* [ ] **Test Case 901**
Step 3 requires read on 7/0, but verification H. of that step refers to resources that belongs to another object - Connectivity Monitoring, id 4.

* [ ] **Test Case 1630** 
  * Resource 2 is Executable, it is not possible to write on it as provided in instruction.
```
{“bn”:”/16/1/0/”,
   “e”:[ 
  {"n":"0","sv":”Host Device ID #2”},
  {"n":"1","sv":”Host Device Model #2”}
]
}
```

**Comment by kFYatek** [comment]
**Test Case 215:**
The SetOfValues does not include the Lifetime resource, so the Replace case (CoAP PUT) of the Write operation fails, because the server attempts to replace valid instance of /1/0 with an invalid instance (lacking a mandatory resource).

**Test Case 260:**
Already reported as issue #234

**Comment by kFYatek** [comment]
**Test Case 1250:**
Test Procedure step 5 is specified as: "Server reads the list of active APN Connection Profiles by performing a TLV READ targeting Resource ID:11 of  Object 10 (/10/11)" - the correct URI paths should be /10/0/11

**Comment by ThGarnier** [comment]
-  Case 901 : yes : yr are right  : step H in pass criteria should concern Resources 0-5 of object 7
-  Case 1630 : could you clarify pls ? : Portfolio object here has   only one Resource ID:0  which is multi-instance with RW attribute : so what about yr question regarding Resource 2 and executable operation ?

**Comment by giuseppe-melis** [comment]
**Test Case 685:**
In Test procedure section, the sentence
"A CREATE operationon targeting the Device Object ID:3 is performed by the Server and received by the Client."
should be removed, because it's an operation not allowed (refer to Test Case 680): [copy&paste from 680?]
Furthermore, in Pass-Criteria section, the sentence
"A. In test step 1, the Server received the requested information (Firmware Version) in the data format preferred by the Client"
should be removed, because there is no READ operation in Test procedure section: [copy&paste from 652?]
Anyway, a good improvement could be:
**Test Procedure:**
READ ... (copy from 652, this step could be a good precondition in order to be sure that the object is present)
1 DELETE as it is
**Pass-Criteria:**
A. In preconditions test step, the Server received the requested information (Firmware Version) ...as it is
B. In test step 1, the Server receives the failure message (4.05 Method Not Allowed) ...as it is

**Comment by softgearko** [comment]
**Test Case 303:**
TS didn't describe this scenario; Cancelling to object Instance performs Cancelling for all observation to  resources in object instance.  However, this may violate RFC 7641, "a client MAY explicitly deregister by issuing a GET request that has the Token field set to the token of the observation to be cancelled and includes an Observe Option with the value set to 1 (deregister).  **All other options MUST be identical to those in the registration request** except for the set of ETag Options.  When the server receives such a request, it will remove any matching entry from the list of observers and process the GET request as usual."

**Comment by ThGarnier** [comment]
As a general rule, and as  already said, please don't put different issues under a single github issue; it is also true for ETS . All issues are addressed here , at least partially so this github issue will be closed : if any comment reopen single issue accordingly : many thanks . Th  

. 303 : in line with the TS 1.0.X  as it is not forbidden to cancel any observation at the Object Instance even if Observation has been done at Resource level before : Violation of RFC 7641 is another story which has to be discussed in the WG . 
.901 :  as said in previous comment,  addressed and fixed in next ETS 
. 1630 : as said in previous comment  the reported issue needs to be clarified 
. 215 : partial write (POST) allows this (5.4.3 & 8.2.5) ; if any inconsistency exists elsewhere please report it (new issue)
. 260 : addressed
. 1250 : yes : good eyes : it will be fixed in next ETS : thanks
. 685 : yes there are bad cut & paste in that test which must be removed : fixed in next ETS  thanks
