### ISSUE TITLE
Bootstrap is require to write object 1 with mandatory resources

### ISSUE THREAD

**Issue by szysas** [OpenMobileAlliance/OMA_LwM2M_for_Developers#239]
* `OMA-TS-LightweightM2M-V1_0_1-20170704-A)`
* Section: E.2

During bootstrap process, it is required by bootstrap server to write object 1 to a lwm2m client. 
In that object, there are several mandatory fields that are problematic: 
- `/1/0/1` lifetime: bootstrap server can not know what is the desired client lifetime (different devices might need to use different lifetimes)
- `/1/0/6` Notification Storing When Disabled or Offline: again client should decide this behaviour 
- `/1/0/7` binding: how can bootstrap know if device should use queue mode?

**Comment by kFYatek** [comment]
One interesting observation is that to set the Binding parameter, the Bootstrap Server would need to know what bindings the client supports. That information is exposed by the device in the /3/0/16 (Supported Binding and Modes) resource, but the Bootstrap Server cannot query that, because there is no Bootstrap Read operation.

Side note: the format of the /3/0/16 resource is specified in a rather confusing way, but that's another issue.

**Comment by fdur** [comment]
This is a very insteresting post.
Does the client need to know the lifetime value set by the bootstrap server ?
This parameter is linked to client registration on server side.
Moreover, the "Device management" server can update the lifetime value. This is a "system parameter": client-server parameter.
From my point of view, the priority for the lifetime is the server value.
If the client updates this parameter value, a registration update message needs to be sent to the devcie managmeent server, and on each connection to the bootstrap server, the client needs to check the lifetime value.

For `/1/0/6`, I've no idea.

For `/1/0/7`, without queue mode, in UDP, I don't know how it could work :)

**Comment by Echo-xubei** [comment]
In my understanding, the bootstrap server is used to set the common bootstrap information for a batch of LwM2M clients, not for the specified one. These LwM2M clients have the same attributes before impletation. These attributes are determinded by the service. 
For example, if the LwM2M client is hosted on a water meter, the meter  report the data to the Server every 24 hours. After data reporting, the meter should be in power saving mode.
In this use case, /1/0/1 lifetime should be more than 24 hours to save the power consumption.
/1/0/6 should be true because  the LwM2M Client needs stores “Notify” operations to the LwM2M Server while the LwM2M Client is in powere saving mode.
/1/0/7 shoud be queue mode.
So the information is available before performing the Bootstrap procedure. 
In addition, even the service information can not be available, the bootstrap server can set the default value for the LwM2M Clients. After the registration,the LwM2M Server can update the values of these resources according to the requirement.
At last, in TS 5.2.2, there is the description:
_This Bootstrap Information can be available before performing the Bootstrap Sequence described in Section 5.2.4 or obtained as a result of the Bootstrap Sequence._

**Comment by hannestschofenig** [comment]
I believe the simplest approach is to make these resources optional. For those cases where the server knows the values upfront they can be provisioned during bootstrapping by the server and in other cases the client would have to populate them.

**Comment by hannestschofenig** [comment]
Another thought: just because the resources are indicated as mandatory does not mean that the bootstrap server needs to write those values in there. It just means that once an instance is created the resource needs to be present. Whether the value actually comes from the server or from the client is another story. 

How does that sound?

**Comment by szysas** [comment]
>  just because the resources are indicated as mandatory does not mean that the bootstrap server needs to write those values in there

That's a good point. Could there be clarification in a spec, about it, to avoid future misunderstanding?

**Comment by kFYatek** [comment]
While it's true that these values might come from either Bootstrap Server or the client, these values are part of a Server Account; it only makes sense for them to exist upfront if some non-bootstrap LwM2M Server is already pre-provisioned (e.g. via Factory or Smartcard Bootstrap mode) at the time of communicating with the Bootstrap server - which, according to section 5.2.4, basically disables Client-Initiated Bootstrap.

It doesn't seem to make sense if the Bootstrap Information coming from Factory or Smartcard would contain a Server object instance, but no corresponding Security instance - and if both valid Security and Server instances for a regular server exist, Client-Initiated Bootstrap is not performed. So in case of a Client-Initiated Bootstrap, in my understanding, the Bootstrap Server needs to be prepared to create the Server object from scratch.

**Comment by Echo-xubei** [comment]
These resources are mandatory for the device management function whether they are optional or mandatory in the object. They must have values upfront the LwM2M Client performs registration to the LwM2M Server.
If we can reach agreement on the above, it means the values of these resource must be set during the bootstrap procedure however. So which Bootstrap Mode to finish it should not be a problem any more.

**Comment by hannestschofenig** [comment]
Mojan says that if the resource is not mandatory then you might end up in the situation where the server cannot change the registration lifetime when the client does not support this lifetime resource

**Comment by hannestschofenig** [comment]
Mojan says that we should add text regarding the behavior: when the server writes to this resource then the client should immediately send a registration update.

**Comment by hannestschofenig** [comment]
If this issue is still valid, please re-issue it against the LwM2M v1.1 release.
