### ISSUE TITLE
cosmetic mistakes in spec

### ISSUE THREAD

**Issue by giuseppe-melis** [OpenMobileAlliance/OMA_LwM2M_for_Developers#246]
OMA-ETS-LightweightM2M-V1_0_1-20170830-D.pdf and
OMA-ETS-LightweightM2M-V1_0_1-20170926-A.pdf
just cosmetic issue:
a) "operation**on**" to be replaced with "operation on" in section 6.1.6.4.9 and 6.1.6.4.10

OMA-TS-LightweightM2M-V1_0_1-20170704-A.pdf
just cosmetic issue:
b) "syntax bel**l**ow" to be replaced with "syntax below" in section 5.4.5

**Comment by hannestschofenig** [comment]
Thanks. Thierry will fix these typos in the ETS spec and the other issue will be fixed in v1.1

**Comment by ThGarnier** [comment]
Thanks, addressed in link with issue #236 (ETS)

**Comment by giuseppe-melis** [comment]
OMA-TS-LightweightM2M-V1_0_1-20170704-A section 8.2.5 pag. 78(141):
c) The Discover operation **(**uses a CoAP GET ...  --> **(** to be removed

**Comment by giuseppe-melis** [comment]
According to spec OMA-TS-LightweightM2M-V1_0_1-20170704-A section 5.1.2 and table 4:
the "CoRE Link param" for Step attribute is "st", not "stp" (maybe it has been modified than old TS versions...)
so, this cosmetic issue should be fixed:
OMA-TS-LightweightM2M-V1_0_1-20170704-A section 8.2.5 pag. 78(141):
d) "Write-Attributes /3/0/9?gt=45&**stp**=10..." to be replaced by "Write-Attributes /3/0/9?gt=45&**st**=10..."
e) "Write-Attributes /3/0/9?lt=20&gt=85&**stp**=10..." to be replaced by "Write-Attributes /3/0/9?lt=20&gt=85&**st**=10..."

Furthermore, since some servers at TestFest sent **stp** parameter to my client, can it be accepted as backward compatibility?

**Comment by ThGarnier** [comment]
Yes Giuseppe;  good eyes
TS :   d) and e) have already been fixed in TS 1.0.2
         c) will be fixed asap 

Please for any new issue, open a new one, otherwise no way to close old ones :)  many thanks

**Comment by brianvandenBerg** [comment]
GitHub Free OpenSource For Profit “File Sharing” Methods...

Transmitting Private Internal Voice Vibration Radio Frequencies....

To Alexa compatible devices...


My Software was Stolen by a girl...

Now the main stream media seems to be “tuned” into my 
Baseline “Private” Internal Voice Vibrations Radio Frequencies....

I need a Patent attorney since my “Tech” doesn’t exist...cough cough..

OpenSource “Speech Recognition Software”...

Who works for free...?

OpenSource is Free...

File sharing with the OpenSource Licensing applied is legal...@FBI nor any other can/will do anything...


Like MUSIC....buy ONE copy...

source code...

apply your logo/name and...apply 

Apache or 
Free BSD Licensing 



Sale a Million$$$$....

It’s legal 

#LeftFlutterEH do I continue? 
Pay me for my Services..

@Outcomes_Matter for more Free “Methods” & Sources...

Because I haven’t been paid....I will give away all the secrets....@Outcomes_Matter 


Brian VandenBerg 
620-249-0771 
Lamar, Mo 64759


> On Jun 19, 2018, at 10:38 PM, Mark <notifications@github.com> wrote:
> 
> Many thanks!
> 
> Sent from my iPhone
> 
> > On Jun 19, 2018, at 6:19 PM, Birgit Pauli-Haack <notifications@github.com> wrote:
> > 
> > I would think it is related to the Visual Composer, too. They published an article how to make your site Gutenberg ready with the Gutenberg Element within Visual Composer. You can read up about it herehttps://visualcomposer.io/gutenberg-compatibility-and-element/
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Brian VandenBerg 
620-249-0771 
Lamar, Mo 64759
