### ISSUE TITLE
Device data enhancement to support advanced sub-modules

### ISSUE THREAD

**Issue by lauri-piikivi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#253]
Lightweight Machine to Machine Technical Specification
Approved Version 1.0.1 – 04 Jul 2017
OMA-TS-LightweightM2M-V1_0_1-20170704-A

Chapter: E.4 LwM2M Object: Device

The device information: 
- Manufacturer
- Model Number
- Serial Number
- Firmware Version

is defined as single instance for single instance object. It would be helpful to be able to define sub-modules with that information in the device. For example a device may have cellular modem, and that modem has separate information from the 'master' device. For device inventory and SW updates, separating that information would be needed.

**Comment by ThGarnier** [comment]
Hello,  some people for addressing sub-mobule infos your are speaking about, are using the capability of the Device Object to be extended through the ExtDevInfo Resource (ID:22) ; This Multiple-Instances Resource can be used to point to other Object Instance(s)  (Instance of Portfolio Object in your case could be a possibility) . Is it what you are looking for ? otherwise, maybe you could provide typical example . 
Hope it helps
Th

**Comment by hannestschofenig** [comment]
Maybe we should address this functionality in v1.1 since the issue of only having a single instance firmware image has been raised in the past as well.

**Comment by dnav** [comment]
For multiple firmware images, there is the Software Management Object (ID: 9)
http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?url=http%3A%2F%2Fwww.openmobilealliance.org%2Ftech%2Fprofiles%2FLWM2M_Software_Management-v1_0.xml

**Comment by hannestschofenig** [comment]
It would be useful to clarify the boundaries and relationship between the firmware update and the software management functionality.

**Comment by hannestschofenig** [comment]
The existing information should be sufficient.
