### ISSUE TITLE
New Content Type: registration with IANA & CoAP ID entry

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LwM2M_for_Developers#26]
At the testfest event it was agreed that OMA should register with IANA the following content type: (as it is unique to LwM2M)
         application/vnd.oma.lwm2m+tlv

Also, it was discussed that the content type
    application/vnd.oma.lwm2m+json  
didn't need to be registered with IANA but it was suggested to check with SENML (IETF), still in draft. Matthias Kovatsch agreed to check this point.

Also, later on was suggested that all the content types need to get from CoAP an entry ID (integer value) in the CoAP register.
At the event we used the following types:
- Plain Text - 1541
- TLV        - 1542
- JSON       - 1543
- Opaque     - 1544
  In future events this needs to be resolved.

The following types was suggested that don't need to be registered with IANA as already exist: 
-   Plain Text
          application/vnd.oma.lwm2m+text 
-   Opaque
          application/vnd.oma.lwm2m+opaque   NO, 42(application/octet-stream)

OMA WG is requested to review this problem and provide a resolution to OMA staff to initiate the necessary steps.

**Comment by ThGarnier** [comment]
The CR09 R02  (2015-02-12) started to solve this issue in specifying the re-use of IANA Media Type plain/text & application/octet-stream with their associated Numerical Coap  value (0 and 42).
registration of application/vnd.oma.lwm2m+json is certainly needed due to the fact SENML doesn't support objlnk data type and OMA LWM2M has no reason of being fully linked to SENML 
registration of application/vnd.oma.lwm2m+json & application/vnd.oma.lwm2m+tlv should be on going for being ready for next plug test.

**Comment by ThGarnier** [comment]
This issues are addressed & fixed in  OMA-TS-LightweightM2M-V1_0-20150910-D
=> to be closed

**Comment by boaks** [comment]
PLEASE:

DON'T CLOSE THIS UNTIL THE IANA VALUES ARE AVAILABLE!

I DON'T SEE THEM IN OMA-TS-LightweightM2M-V1_0-20151211-D, 6.3. THERE STILL "TDB"

ARE THERE SOMEWHERE ELSE?

**Comment by ThGarnier** [comment]
Media types registered to IANA,  OMA waiting for IETF to  allocate  CoAP values for them

**Comment by hannestschofenig** [comment]
Media types have been registered.
