### ISSUE TITLE
OMA LwM2M defines more mandatory functionality than in CoAP

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LwM2M_for_Developers#28]
The attendees to the Dusseldorf LwM2M TestFest indicated that in general  OMA LwM2M specifications define more mandatory functionality than in CoAP.
Friedhelm Rodermund from Vodafone, took an action item on to further investigate this perception.

**Comment by ThGarnier** [comment]
Any concrete examples ?  I've no idea

**Comment by boaks** [comment]
"Observe" is marked as **option** in CoAP (RFC7252, 2.2. page 14) and as **MUST** in LwM2M (TS 20150513, 5.5, page 31).

**Comment by ThGarnier** [comment]
Regarding "Observe"  YES ! LWM2M considers it's an essential and basic  functionality to support to address M2M segment. 
It is even so true that without that feature, LWM2M will be even not able to Interwork with oneM2M.
Other example ? maybe you are right for other features.

**Comment by ThGarnier** [comment]
Ok no other comments for 6 months  => to be closed

**Comment by jvermillard** [comment]
IMHO: For device management LWM2M is totally usable without observe (real world experience here). 
Now for OneM2M compatibility, I don't doubt a massive standard like OneM2M needs a tons of mandatory features :)

**Comment by ThGarnier** [comment]
no new remark => to be closed

**Comment by sbernard31** [comment]
This seems to be a new and real remark ...
> IMHO: For device management LWM2M is totally usable without observe (real world experience here).
Now for OneM2M compatibility, I don't doubt a massive standard like OneM2M needs a tons of mandatory features :)

I didn't know that being compatible with OneM2M was mandatory for LWM2M ...
> It is even so true that without that feature, LWM2M will be even not able to Interwork with oneM2M.

**Comment by subhashnairp** [comment]
Onem2m already very focused on interworking with LWm2m.But as you told
device management in LWm2m also include application managemnt .
      While onwM2m have more alignment with OMA DM and BBF, it is confusing
how the read/write/observe can be mapped to oneM2m. Onem2m only support
enable/disable feature through a device capability resource .
      Would like to more opinions regarding this
Regards
Subhash

On Apr 15, 2016 2:28 PM, "sbernard31" <notifications@github.com> wrote:

This seems to be a new and real remark ...

IMHO: For device management LWM2M is totally usable without observe (real
world experience here).
Now for OneM2M compatibility, I don't doubt a massive standard like OneM2M
needs a tons of mandatory features :)

I didn't know that being compatible with OneM2M was mandatory for LWM2M ...

It is even so true that without that feature, LWM2M will be even not able
to Interwork with oneM2M.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/28#issuecomment-210370253>

**Comment by ThGarnier** [comment]
in oneM2M, when we speak about LWM2M interworking, it has nothing to do with Device Management . 
It is at the service layer that LWM2M is interworked (as OMA DM and BBF TR069 can't do) .
At one moment it has been decided that LWM2M must support Observe functionality to serve IoT application at the best. CoAP is a bit more general that  LWM2M, it is normal that few capabilities 
remain optional according the final goal  (for instance in oneM2M, CoAP can be used exactly in replacement than HTTP) . 
also use that vector as it could use HTTP

**Comment by Megan-OMA** [comment]
Observation lifetime and registration
