### ISSUE TITLE
[need-clarification] actions after receiving reboot command

### ISSUE THREAD

**Issue by GiedriusM** [OpenMobileAlliance/OMA_LwM2M_for_Developers#280]
When submitting an issue please indicate the following information:
* Name, version and date of the document: OMA-TS-LightweightM2M-V1_0_1-20170704-A
* Section of the document: Appendix E.4
* Sequence of exchanges between Client and Server:  Execute Reboot resource (/3/x/4)

The reboot resource description is short and it is unclear what SHOULD (NOT) and MUST (NOT) be done:
```
Reboot the LwM2M Device to restore the Device from unexpected firmware failure.
```
Other resources (for example /1/x/4, /3/x/5) are described in more detail.

Some questions that come to my mind:
1) Can the device reboot immediately? What if it reboots fast enough and receives a re-transmission of a previous CoAP request (execute reboot)?
2) Should it send response code and only then reboot? What if it fails to send a response, i.e. CoAP confirmable response message is not ACKed or any other error occurs?
3) Should it send a de-registration?
4) In general, if it's not an immediate execution and other steps have to taken, how should the errors be handled? Reboot no matter what or halt the reboot? Is there any time-out window in which the reboot has to happen?

**Comment by fdur** [comment]
FMPOV:

> 1) Can the device reboot immediately? What if it reboots fast enough and receives a re-transmission of a previous CoAP request (execute reboot)?

It depends on client implementation and also on application behavior. If some applications are embedded, the reboot needs to be "agreed" by these applications ...

> 2) Should it send response code and only then reboot? What if it fails to send a response, i.e. CoAP confirmable response message is not ACKed or any other error occurs?

I discussed quickly about it at: https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/209#issuecomment-311964608
FMPOV, the device needs to send the response and then reboot ... but it's not really clear

> 3) Should it send a de-registration?

This is a client behavior. I suggest: yes

> 4) In general, if it's not an immediate execution and other steps have to taken, how should the errors be handled? Reboot no matter what or halt the reboot? Is there any time-out window in which the reboot has to happen?

If the reboot is not immediate and if the device acks the reboot request, no error could be handled ... or I don't know how

**Comment by GiedriusM** [comment]
@fdur, well I'm still undecided about this. Can't really think of any decent arguments for this case, could go either way... One thing that I would be against is to send response code after the reboot, because reboot is supposed to clear any information of a previous state, including registration status, DTLS sessions or anything else.
I, personally, lean towards sending a response and then rebooting, however it's still unclear what to do if the response fails to be sent. Cancel the reboot?

**Comment by fdur** [comment]
FMPOV, if the response can not be sent by the client, the commnd should not be processed, becasue the server is not achknowledged ... Then CoAP retry coul be launched on server side.

**Comment by sbernard31** [comment]
**A)** The ideal scenario could looks like this :
```
Device                                  Server
  |                                       |
  | <-------- Reboot request -----------  |
  | -----------  ACK   -----------------> | 
  X Reboot
  | ------------ CON 2.04 Changed ------> |
  | <-----------  ACK   ----------------- | 
```
But to be able to do that, device should persist a lot of state (CoAP exchange state, DTLS state...) Persisted CoAP will allow to handle retransmission/duplicate too.
Separated response after reboot can be use to handle issue with reboot (returning an error instead of 2.0.4)
When server receive the SUCCESS response it can send next requests immediately.

It sounds perfect but I didn't know CoAP or DTLS implementation which can persist this kind of state. 
So it sounds not so good... 

**B)** So let's imagine a solution where we don't persist state.
```
Device                                  Server
  |                                       |
  | <-------- Reboot request -----------  |
  | --- PIGGYBACK ACK 2.04 changed  ----> | 
  X Reboot
  |  
```
But your are right, if you don't persist CoAP state, you will not be able to detect potential retransmission if PIGGYBACK is lost. 
This means potential reboot in loop ... clearly the worst solution ...

**C)** So another solution  
```
Device                                  Server
  |                                       |
  | <-------- Reboot request -----------  |
  | -----------  ACK   -----------------> | 
  | ------------ CON 2.04 Changed-------> |
  | <-----------  ACK   ----------------  | 
  X Reboot
```
This solve the retransmission issue as you ensure response is well received before to reboot.

Problems : 
- Server is not aware if reboot is success or failure.
- Server is not aware when the reboot is done. (So server does not know when it can send next request and so could send next request during device rebooting...)

**D)** Another try, 
```
Device                                  Server
  |                                       |
  | <-------- Reboot request -----------  |
  |  ----------  ACK   -----------------> | 
  |  ----------- CON 2.04 Changed-------> |
  | <-----------  ACK   ----------------  |
  |  (Device should ignore all requests   |
  | from server until it register again)  |
  |  --------  Deregister request ------> |
  | <----- PIGGYBACK 2.02 Deleted-------  |
  X Reboot
  | -----   Register request  ----------> |
  | <----- PIGGYBACK 2.01 Created ------  |
```
This solve the retransmission issue as you ensure response is well received before to reboot.
We use deregister/register to say to the server "don't send me request anymore".

Problems : 
- Server is not aware if reboot is success or failure.
- This force device to deregister/register and some server could send you specific request each time you register so this could generate undesired traffic.

Conclusion, I can not find any good solution without spec modification...

With spec modification we could maybe imagine a kind of solution with a resource containing the device state inspired from firmware update ?

Anyway I think we need a fix for version 1.0.2 or 1.0.3 ...

**Comment by fdur** [comment]
I totally agree with you Simon !!!
Thanks for all possibility descriptions :)
I really don't know how server can know that the reboot was made ....

**Comment by GiedriusM** [comment]
@sbernard31 that's a really detailed thought :)
From implementation point of view, if A scenario was mandatory it could really be a killer requirement for many platforms. IMO the reboot should clear any soft-state information (observations, registrations, DTLS sessions, etc.). If after reboot the client MUST re-register and the server MUST clear any pending transactions on client registration, then the multiple reboot problem is resolved.

Also it may be difficult to impose transport specific requirements, such as in B vs C, because some CoAP implementations may not have such features. Additionally messages could be sent over SMS.

Seeing as there's little hope for a decent reboot confirmation, I'm thinking that maybe the (missing) "execute reboot" response requirement could be relaxed and other features used, such as a "device uptime" resource. What are your thoughts on following suggestions:
* When the client receives "EXEC reboot": If reboot procedure/scheduling fails it MUST send an error response, otherwise it SHOULD send a success response (if reboot is scheduled), but it CAN skip the response (if reboot is executed immediately).
* Once reboot is scheduled, the client MUST NOT send update messages.
* If device scheduled a reboot and it is in non-queue mode, it SHOULD send a deregistration.
* When the device reboots it MUST (clear all soft state and) send a new registration.
* Client MUST/SHOULD support "uptime" resource.
* The server SHOULD NOT treat missing response to "execute response" as a (critical) error. Instead it SHOULD expect a new registration. If new registration is not received within X timeframe or an update is received "execute reboot" should be considered failed operation. Upon reregistration the server (or to be more precise, a reboot command issuer) MUST cancel all pending/failed transactions and resend all observation requests. It SHOULD read client "uptime" resource to validate a successful reboot.

P.S. I am not sure if restriction on the updates is really needed here.
P.P.S. Instead of "uptime" resource, an additional registration (reason) parameter could be introduced `/rd?ep=foobar&rr=reboot`

**Comment by sbernard31** [comment]
> If after reboot the client MUST re-register and the server MUST clear any pending transactions on client registration, then the multiple reboot problem is resolved.

Yes, it is but only if we consider race condition will not happen.

> When the client receives "EXEC reboot": If reboot procedure/scheduling fails it MUST send an error response, otherwise it SHOULD send a success response (if reboot is scheduled), 

It sounds good to me to say that a success response means "Reboot scheduled", but now we need to know if the reboot is a success and when?

> but it CAN skip the response (if reboot is executed immediately).

So the server will continue to send retransmission, if response is lost or just not sent, right? Or does it means that reboot command should be a CoAP Non-confirmable message ? In that case , there is a  risk the reboot request was just lost.

> Client MUST/SHOULD support "uptime" resource.

I didn't find this "uptime" resource in the spec ? You propose to add this ?

But using this uptime, we can maybe imagine a solution like : 
- Read Uptime Resource. (keep uptime `uptime1` + date we get the uptime `date1`)
- Exec Reboot Resource. (which means we schedule a reboot)
- Wait For Device communicate (Register or Update), that's means client MUST send a request in all case success or failure.
- Read Uptime Resource. (`uptime2` + `date2`)

if (uptime2 - (date2-date1) < uptime1), it means success, else it is failure.
But playing with date could maybe causes some troubles with network delay and retransmission.

> P.P.S. Instead of "uptime" resource, an additional registration (reason) parameter could be introduced /rd?ep=foobar&rr=reboot

I feel more confident with a solution like this but this force device to maintain a kind of state to know this is a reboot.

**Comment by GiedriusM** [comment]
> >If after reboot the client MUST re-register and the server MUST clear any pending transactions on client registration, then the multiple reboot problem is resolved.
> 
> Yes, it is but only if we consider race condition will not happen.

What race condition do you have in mind? If after reboot client MUST have it's soft-state (including registration) cleared, then any stray request will be ignored. The only way I see this happening is if server sends reboot retry before it receives registration request, but registration response reaches the client first, i. e. packet reordering happens. Well, if so, then the worst that can happen to this very unlikely circumstance is another (single) reboot. And it should not happen if DTLS is used.

>> but it CAN skip the response (if reboot is executed immediately).
> 
> So the server will continue to send retransmission, if response is lost or just not sent, right? Or does it means that reboot command should be a CoAP Non-confirmable message ? In that case , there is a risk the reboot request was just lost.

The server will just keep sending retries until the client re-registers or maximum re-transmission is reached. This simplification is proposed having in mind that response message is not an indication of successful reboot and it should be determined by other means ("uptime" resource, "rr" parameter, etc). Execute reboot could also have a standardized parameter "forced reboot" or "timeout=0", which would be useful in cases where for some reason scheduled reboot fails.


>> Client MUST/SHOULD support "uptime" resource.
> 
> I didn't find this "uptime" resource in the spec ? You propose to add this ?

Currently it's more of "what do you think" rather than proposal, but yes.


>> P.P.S. Instead of "uptime" resource, an additional registration (reason) parameter could be introduced /rd?ep=foobar&rr=reboot
> 
> I feel more confident with a solution like this but this force device to maintain a kind of state to know this is a reboot.

It could be done in slightly different manner - "registration counter" which at startup by default is zero and is incremented every time a successful registration response is received. It could also be just like "uptime" resource, but instead in count units rather than seconds. One issue is that it would indicate  LwM2M client reset/reinitialization rather than an actual hardware reboot.

**Comment by sbernard31** [comment]
> Well, if so, then the worst that can happen to this very unlikely circumstance is another (single) reboot. And it should not happen if DTLS is used.

This is what I was thinking, but you're with DTLS this should not happened.

> It could be done in slightly different manner - "registration counter" which at startup by default is zero and is incremented every time a successful registration response is received. It could also be just like "uptime" resource, but instead in count units rather than seconds. One issue is that it would indicate LwM2M client reset/reinitialization rather than an actual hardware reboot.

All that's solution sounds interested. Hard to make a choice. I never implement a "reboot" resource. What is the good way to know we actually success to reboot at device side ? I mean technically ?

**Comment by GiedriusM** [comment]
In most if not all cases, the successful reboot will result in full system re-initialization, including the LwM2M client. Failed reboot should result in LwM2M client running (sending updates) and not sending a new registration with zeroed reset counter. This will be detected by server (application) and interpreted as failed reboot. One possible false positive is if reboot command is received, system reset task is scheduled and some error happens which forces LwM2M application to be restarted, so reboot task is canceled, but the client re-registers with `rc=0`. It could be solved with a system-wide registration counter, but then what should be done about systems with multiple LwM2M clients? UUID based registration counter? I still think that an (optional) system uptime resource coupled with re-registration counter (which is set to zero on client initialization) could be sufficient.

> What is the good way to know we actually success to reboot at device side ? I mean technically ?

On something like a microcontroller writing to a reset bit forces an instant reset and that's pretty much it.
```C
void init(void) {
    // this only happens after reboot
   global_rc = 0;
}
bool reset(void) {
    SOME_CORE_REGISTER |= SYSTEM_RESET_BIT; // forces instantaneous system reset
    // if we reached here, then there's probably an issue with the hardware
   return false;
}
```

On linux you can check when was the last reboot:
```
$ last reboot
wtmp begins Thu Feb  1 15:00:48 2018

$ uptime
 16:06:14 up 34 days,  3:37, 16 users,  load average: 0.49, 0.36, 0.39
```

**Comment by sbernard31** [comment]
> Failed reboot should result in LwM2M client running (sending updates) and not sending a new registration with zeroed reset counter

I know some proprietary implementation which sent update after a reboot and are able to persist some observation relation after a reboot. So I don't know if receiving an update should be consider as a failed.

**Comment by hannestschofenig** [comment]
> * Can the device reboot immediately? What if it reboots fast enough and receives a re-transmission of a previous CoAP request (execute reboot)?

This is implementation dependent. 

> * Should it send response code and only then reboot? What if it fails to send a response, i.e. CoAP confirmable response message is not ACKed or any other error occurs?

It is a POST message it requires a response. Hence, there will be a response (2.04).

* Should it send a de-registration?

> It is not mandatory to do a re-registration but the device could do that. It is implementation dependent. 

> * In general, if it's not an immediate execution and other steps have to taken, how should the errors be handled? Reboot no matter what or halt the reboot? Is there any time-out window in which the reboot has to happen?

Which error? If there are errors during reboot it depends on what the cause of the error is, which will be implementation dependent. 

As a summary, there is no interoperability issue that requires specification changes.

**Comment by sbernard31** [comment]
It's a bit easy to say : it's implementation dependent.
I would be ok with that if we have tools available to handle issues raised in this thread : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/280#issuecomment-363483045

**Comment by GiedriusM** [comment]
> > * Can the device reboot immediately? What if it reboots fast enough and receives a re-transmission of a previous CoAP request (execute reboot)?
> 
> This is implementation dependent.
> 
> > * Should it send response code and only then reboot? What if it fails to send a response, i.e. CoAP confirmable response message is not ACKed or any other error occurs?
> 
> It is a POST message it requires a response. Hence, there will be a response (2.04).

These two answers are self-contradictory: if in the first case implementation decides to reboot immediately (i. e.  set SoC reset register) it will not be able to fulfill the second case and send and ACK. 
It also doesn't address the case if the response itself is lost. I **guess**\* the device should not reboot if it did not get an ACK to a response. But then there's a situation in which server receives the response, sends an ACK, which is lost in transmission. The server will think that the device rebooted, even though device has actually did not do it because it did not receive an ACK to the response.

---
\* is a standard supposed to be interpreted by guessing?

**Comment by fdur** [comment]
I think that a client can not reboot without sending the ACK.
In such case, if the device 
In LwM2M 1.0 spec, §8.3:
> If message delivery fails, for example, because the message got lost due to network connectivity issues or because the LMW2M Client was sleeping then CoAP re-transmission behaviour at the LwM2M Server will try to retransmit the message. The CoAP stack at the LwM2M Server will resend the message up to a certain number of attempts, as described in Section 4.2 of [CoAP].

My interpretation in this case is that if the clients immediately reboots and connect again to the server before the CoAP retransmission timer expiry, the server could be able to send again the reboot request.
So, FMPOV, immediate reboot on client side without sending an ACK to the server before the reboot does not really respect the LwM2M spec

**Comment by GiedriusM** [comment]
> I think that a client can not reboot without sending the ACK.

I could agree with such requirement.

> My interpretation in this case [...]

That's the issue. Some cases are non-trivial to say the least, with multiple possible solutions. However different developers interpret differently. So in theory any proper LwM2M client should work with any proper LwM2M server, but in practice proprietary/in-the-house solutions are starting to pop-up which may "technically" be within the spec, but workarounds have to be introduced to resolve the "interpretation" discrepancies.
So even in the case where requirement cannot be made due to existing solutions in the field, a recommendation or preferable solution would a lot more appreciated than an "implementation dependent" response, which we all know what it actually means :)

**Comment by hannestschofenig** [comment]
We can, of course, add text to the spec to provide extra clarity. In the description of the Execute Reboot resource we could indicate that the device must send a ack before rebooting since the Post message requires a response. We could also say that the device may do a re-registration but this step is not mandatory. 

Do you think this would be an improvement over what we have in the spec today?

**Comment by GiedriusM** [comment]
> Do you think this would be an improvement over what we have in the spec today?

Yes, this would definitely help, thank you.

> We can, of course, add text to the spec to provide extra clarity. In the description of the Execute Reboot resource we could indicate that the device must send a ack before rebooting since the Post message requires a response. We could also say that the device may do a re-registration but this step is not mandatory.

This sounds good. As far as I understand, this is scenario C in https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/280#issuecomment-363483045? IMO this is the best solution, that does not require any further changes, however it still has specific issues, namely, that the server only knows the reboot was scheduled and not that it was executed.
In __v1.1__ spec section __6.4.1 Observe__, there's a statement `In order to avoid network traffic increase, the LwM2M Client SHOULD maintain previous observation states in case of reboot, power cycle.`, so the last sentence would become a slight contradiction. Although IMPO reboot should clear any soft states, including connection and registration status, but I assume things are different in cellular deployments :)

**Comment by sbernard31** [comment]
> In the description of the Execute Reboot resource we could indicate that the device must send a ack before rebooting since the Post message requires a response.

It seems to me that this sentence just mean that [B scenario](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/280#issuecomment-363483045) is excluded. and for me It's not so clear as PIGGYPACK is a kind of ACK.

If we want to exclude B, we should rather indicate that for this resource :
- the server request MUST?/SHOULD? be confirmable.
- the device MUST?/SHOULD? answer with a (confirmable?) separated response ? This clearly excludes B and this allow A,C,D...

But I feel this does not really solve any issue expressed in https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/280#issuecomment-363483045

**Comment by sbernard31** [comment]
@GiedriusM, @hannestschofenig 

As there is still no way in the specification to be sure a reboot was done successfully
I would like to propose to register a new object, maybe something like `DeviceExt`

For now and to resolve our use case I think we need only few resources. (but more could be added later)

I list here all the solutions exposed above to initiate a discussion : 

### Last reboot
| Id | Name  |Op | Inst| Mand |Type|R | U | Description |
|---|---|---|---|---|---|---|---|---|
| 0 | Last Reboot  | R  | Single  | Mandatory  | Time  |  |  | Last reboot time | 

The server need to read the value before and after the EXEC on reboot resource (3/0/4), then compare to know if this is a success.
No way to really detect a failure. (except an unreliable timeout)
On Linux this is easily available using `last reboot -n 1 -R --time-format iso`.
The device need to keep the good time.

### Boot counter
| Id | Name  |Op | Inst| Mand |Type|R | U | Description |
|---|---|---|---|---|---|---|---|---|
| 0 | Boot Counter  | R  | Single  | Mandatory  | Integer  |  |  | counter of boot, it should be incremented at each system boot | 

The server need to read the value before and after the EXEC on reboot resource (3/0/4), then compare to know if this is a success. 
No way to really detect a failure. (except an unreliable timeout)
AFAIK there is no easy way to get this information on Linux, maybe something like counting the number of line of `last reboot` but that sounds not so reliable.

### Uptime
| Id | Name  |Op | Inst| Mand |Type|R | U | Description |
|---|---|---|---|---|---|---|---|---|
| 0 | Uptime  | R  | Single  | Mandatory  | Integer  |  |  | The total number of seconds the system has been up | 

The server need to read the value before and after the EXEC on reboot resource (3/0/4), then compare to know if this is a success.
No way to really detect a failure. (except an unreliable timeout)
On Linux could be available using `cat /proc/uptime`
This issue here, we could face some false negative if :
 - the previous value is too low
 - the server read the resource after too many time

### Reboot Result
| Id | Name  |Op | Inst| Mand |Type|R | U | Description |
|---|---|---|---|---|---|---|---|---|
| 0 | Reboot Result  | R  | Single  | Mandatory  | Integer  | 0-2 |  |  Contains the result of reboot state. At device start up the value is set to 0 (success). Once the reboot process is scheduled (exec on /3/0/4). This value must be set to 1(rebooting). If rebooting fails value must be set to 2(error). If reboot success, device should set it to 0 (success) as always.
| 1 | Reboot Error Message  | R  | Single  | Optional  | String  |  |  | Containing the error message of the last reboot failure. This value MUST be set to an empty string on exec on /3/0/4 | 

Server need only to read after the EXEC on reboot resource (3/0/4).
Error is easily known.
Pretty much the same pattern as Firmware Update.
Need probably more work at client side.

(Maybe something like this could be used for reset factory too ? :thinking: but maybe not so easy to keep a state before and after a reset factory)

**Comment by sbernard31** [comment]
An object is proposed at OMA : https://github.com/OpenMobileAlliance/lwm2m-registry/issues/502

To discuss about the PR : https://github.com/OpenMobileAlliance/lwm2m-registry/pull/504

**Comment by sbernard31** [comment]
The object was accepted and is available in [LWM2M registry](https://github.com/OpenMobileAlliance/lwm2m-registry) : Object ["Reboot Status"(10371)](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/10371.xml)

This fixes the problem but ideally those features should be added in Device Object (see https://github.com/OpenMobileAlliance/lwm2m-registry/pull/504#issuecomment-677443802)

**Comment by sbernard31** [comment]
@hannestschofenig  do you talk at OMA about this issue to know if those should be added to Device object (or another official one) ?
