### ISSUE TITLE
OMNA-Registration of oA Device

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#312]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-05-09 11:35:19 UTC</td></tr><tr><td>Submitter's name</td><td>Georg Kuenz</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Zumtobel Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>oA Device</td></tr><tr><td>Object Description</td><td>oA Device</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=3b7470d9-364d-47f3-9041-97a3e754f7f0_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=3b7470d9-364d-47f3-9041-97a3e754f7f0_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Closed due to a number of identified issues with the Objects:
•  Incorrect selection of Object Version
•  Incorrect formation of URN
•  Incorrect allocation of Object ID

Observations: Some of the resources that are utilized indicates that the OpenAIS group should consider creating reusable resources.
