### ISSUE TITLE
Lifetime resource set to value 0

### ISSUE THREAD

**Issue by jaudiger** [OpenMobileAlliance/OMA_LwM2M_for_Developers#381]
Document: OMA-TS-LightweightM2M-V1_0_2-20180209-A
Part:  5.3 Registration

Is it possible to set the resource Lifetime of the Server Object to 0 ? Because actually there is no range value:
![image](https://user-images.githubusercontent.com/31616285/42551183-9c47bbca-8508-11e8-800a-2c8bd7039787.png)

 In that case, what does it mean on the client side?

**Comment by jpradocueva** [comment]
The range should be within acceptable seconds.
DMSE will further discuss this topic.

**Comment by fdur** [comment]
The issue is that a 0-value for lifetime makes no sense according to LwM2M protocol and registration time on server side.
FMPOV, this should means that the device will never be deregistered on server side. This means that the device could send a registration update at any time without being rejected by the server (because the lifetime expiry could not happen).
However, this use case could be interesting :)
Just for information ... I tested this use case using Wakaama several months ago and Wakaama sent in loop registration update messages ....

**Comment by hannestschofenig** [comment]
We don't define the minimum lifetime in the LwM2M specification since a suitable value depends on many factors. Just use sensible values for a given deployment environment.
