### ISSUE TITLE
Question on the security modes(credentials) must supported by Server/Client in LwM2M v1.1

### ISSUE THREAD

**Issue by jaeeunchoi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#392]
In LwM2M v1.0.2 (OMA-TS-LightweightM2M-V1_0_2-20180209-A ), it's clearly explained in the 7.1.7 ~7.1.9.
- Server & Client must support PSK mode.   (means mandatory)
- and other modes are explained with 'if server/client supports...' : (means optional).

But in LwM2M v1.1 ( OMA-TS-LightweightM2M_Transport-V1_1-20180612-C),
There's equivalent chapters ( 5.2.8.1 ~ 5.2.8.3 ), but explains little bit vague.
Server is described 'If a LwM2M supports ...' for all three credentials (psk,rpk, x.509).
And for client, there's no description on which credentials it must support. (There's only comments on ciphersuites.)
And the '5.1 Security Requirements' requires all communication must be encrypted.
-> Does it mean Client and Server must use one of the credentials( security modes) but there's no mandatory credentials?

**Comment by hannestschofenig** [comment]
What this means is the following: 

For interoperability a server has to support all three credential types and a client has to support only one. Which one the client supports does not matter since it will be able to talk to a server in that case. Since the clients are the constrained devices this is a reasonable distribution of responsibilities.

Does this make sense?
