### ISSUE TITLE
The value of PkgName and PkgVersion in LWM2M_Software_Management-v1_0

### ISSUE THREAD

**Issue by Kenny-SZ** [OpenMobileAlliance/OMA_LwM2M_for_Developers#467]
In LWM2M_Software_Management-v1_0, PkgName and PkgVersion are read only.

If I'm installing a new software on a device remotely, I want to know how PkgName and PkgVersion are assigned/decided? Through **Package URI** or **Package**?

Thanks.

B.R.
Kenny

**Comment by Kenny-SZ** [comment]
In addtion, how are Software Components **objLink**ed by **Software Component Link** created?

**Comment by fdur** [comment]
I think that the PkgName/PkgVersion is in fact the software name/version which was installed/updated in the client by sending a package from the server to the client
This package download on client side could be initiated in 2 ways:
1. Package URI when server sends a WRITE command on /9/x/3
2. Package data send over CoAP with WRITE commands on /9/x/2

When the software is installed, this software should be asked in order to retrieved the software name/version when the server sends READ command on /9/x/ and /9/x/1

**Comment by Kenny-SZ** [comment]
> version



> I think that the PkgName/PkgVersion is in fact the software name/version which was installed/updated in the client by sending a package from the server to the client
> This package download on client side could be initiated in 2 ways:
> 
> 1. Package URI when server sends a WRITE command on /9/x/3
> 2. Package data send over CoAP with WRITE commands on /9/x/2
> 
> When the software is installed, this software should be asked in order to retrieved the software name/version when the server sends READ command on /9/x/ and /9/x/1

Thanks a lot for your explanation, actually this is what I'm thinking about, just to confirm if my thought is correct or not. : )
