### ISSUE TITLE
Certificates chain for LWM2M client

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#502]
Hi,
  I would like to get some clarification about how should works certificates chain at client side. (I'm talking about client certs chain validate by the server)

   Reading the specification v1.0 and v1.1, I understand that resource 0/?/3 (Public Key or Identity) contains only the client certificate and not the whole certificates chain. This seems confirmed because  this resource is encoded in DER binary format.

   So my current understanding is that a Bootstrap server is only able to write the client certifcate and not the certificates chain.
   Regarding [rfc5246](https://tools.ietf.org/html/rfc5246#section-7.4.2), 
> certificate_list
      This is a sequence (chain) of certificates.  The sender's
      certificate MUST come first in the list.  Each following
      certificate MUST directly certify the one preceding it.  Because
      certificate validation requires that root keys be distributed
      independently, the self-signed certificate that specifies the root
      certificate authority MAY be omitted from the chain, under the
      assumption that the remote end must already possess it in order to
      validate it in any case.

   Meaning that for TLS/DTLS the whole cert chain is needed (eventually root CA could be omit)

   I came to the conclusion that the only use cases supported are : 
 - client with self-signed certificate
 - client with "Root CA" -> "client Certificate" (as root can be omit)

But  "Root CA"-> ... -> "intermediate CA" -> .... -> "client Certificate" is not supported as there is no way to provide the whole certificate chains.

Or this chains should be provided by another "unspecified" way ? or I missed something ? :sweat_smile: 

 @hannestschofenig, maybe you could give some hint about this ?

**Comment by sbernard31** [comment]
I guess the issue is pretty much the same for resource `Public Key or Identity` (/0/?/3) which is also a certificate and not a certchain. :thinking:

**Comment by hannestschofenig** [comment]
> Reading the specification v1.0 and v1.1, I understand that resource 0/?/4 (Public Key or Identity) contains only the client certificate and not the whole certificates chain. This seems confirmed because this resource is encoded in DER binary format.

You are correct for 0/?/4.

For /0/?/3 the case is a bit different. For v1.0 your statement is correct. However, v1.1 introduced an additional resource called "Certificate Usage", which offers more advanced certificate handling functionality of the server certificate. The details are in the transport spec http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#5-2-8-7-0-5287-Certificate-Usage-Field

For client-side certificates nobody asked for sophisticated certificate chain handling.

**Comment by sbernard31** [comment]
(Sorry I mixed up /0//?/4 (server) and /0/?/3 (client) resources and I think I made you mixed it too, correct ? On my side I fixed my comments. Maybe you should do the same and I remove this comment to make this thread clearer)

**Comment by vesajaaskelainen** [comment]
@hannestschofenig When we are thinking about properly done PKI setup it would involve following.

Server end-points (LWM2M Bootstrap & Server) would have following certificate chain:
- Root CA (Offline CA)
- Intermediate CA (Online CA or so)
- End-Entity Certificate - (D)TLS Server Certificate

Then for client end-points (LWM2M Client) would have similar setup during manufacturing (Initial Device Identity IDevID):
- Manufacturer's Root CA (Offline CA)
- Intermediate CA (Online CA)
- End-Entity Certificate - (D)TLS Client Certificate

Initial Device Identity has special property that those do not really expire so expiry is set to 9999T235959Z or other high number.

Then for client end-points (LWM2M Client) after connected to LWM2M Bootstrap server would transition from manufacturer CA to service specific CA (or Local Device Identity - LDevID) so we would have following:
- Service's Root CA (Offline CA)
- Intermediate CA (Online CA -- could be EST service)
- End-Entity Certificate - (D)TLS Client Certificate

And these service specific TLS Client Certificates would have more saner expiry dates and with services like EST they would be auto renewed.

Now-a-days it is very highly recommended to have separate Offline Root CA so that it is very hard to hijack the CA. This always brings up intermediate CA's in picture.

Now if we map this to LWM2M (1.1.1).

In OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A:

Security Object defines:
- 3 - Public Key or Identity -- Stores the LwM2M Client's certificate, public key (RPK mode) or PSK Identity (PSK mode).
- 4 - Server Public Key -- Stores the LwM2M Server's, respectively LwM2M Bootstrap-Server's, certificate, public key (RPK mode) or trust anchor. The Certificate Mode Resource determines the content of this resource.

Then in OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A - 5.2.8.3. X.509 Certificates:

> The information stored in the "Public Key or Identity" Resource depends on the Certificate Usage Resource, as
> discussed in Section 5.2.8.7. Certificate Usage Field. If the Certificate Usage Resource is missing this Resource
> MUST be used to store the X.509 certificate of the TLS/DTLS client in a DER encoded binary format. This backwards
> compatibility mode matches the semantic of value 3 ("domain-issued certificate") in the Certificate Usage
> Resource.

This defines that _one_ certificate can be encoded as DER in the object when using X.509 Certificates.

So if one uses Security Mode 2 (Certificate Mode) then one cannot provide certificate chain for the client from the server. Another problem with Security Mode 2 is that private key is sent over the wire so not really inviting mode to use.

However if one uses Security Mode 4 - Certificate mode with EST then we have possibility to have full certificate chain supported.

Eg. EST's Simple (Re-)Enroll request would provide you End-Entity Certificate in PKCS#7 container and CA Certificates requests would provide missing parts so that full chain can be constructed (also in PKCS#7 container). 

However now the problem here is that if one wants to store the information in same Security Object it is not syntaxically correct. In theory one could use PKCS#7 container to store the chain in "3 - Public Key or Identity object" or one could use "string" to store PEM cert chain which is slightly easier to differentiate from DER encoded X.509 Certificate.

Then we have a question should we have support to distribute PKCS#7 DER container in "3 - Public Key or Identity field" to allow server to provide full chain to client.

**Comment by dnav** [comment]
Hi,

@vesajaaskelainen wrote:

> Then in OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A - 5.2.8.3. X.509 Certificates:
> 
> > The information stored in the "Public Key or Identity" Resource depends on the Certificate Usage Resource, as
> > discussed in Section 5.2.8.7. Certificate Usage Field. If the Certificate Usage Resource is missing this Resource
> > MUST be used to store the X.509 certificate of the TLS/DTLS client in a DER encoded binary format. This backwards
> > compatibility mode matches the semantic of value 3 ("domain-issued certificate") in the Certificate Usage
> > Resource.
> 
> This defines that one certificate can be encoded as DER in the object when using X.509 Certificates.
>
> So if one uses Security Mode 2 (Certificate Mode) then one cannot provide certificate chain for the client from the server. 

This was indeed the case in LwM2M 1.0.

In LwM2M 1.1, this is the case only if the resource "Certificate usage" (/0/n/15) is missing or has the value 3 ("domain-issued certificate"). [As Hannes pointed out](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#5-2-8-7-0-5287-Certificate-Usage-Field), LwM2M 1.1 allows "CA constraint", "service certificate constraint", and "trust anchor assertion" certificate usages.

> Another problem with Security Mode 2 is that private key is sent over the wire so not really inviting mode to use.

Well, not all devices have the resources to generate a strong key pair. Note that EST is also provides this feature with Server-Side Key Generation where the private key is also sent over the wire.

> However if one uses Security Mode 4 - Certificate mode with EST then we have possibility to have full certificate chain supported.
> 
> (...)
> 
> However now the problem here is that if one wants to store the information in same Security Object it is not syntaxically correct. In theory one could use PKCS#7 container to store the chain in "3 - Public Key or Identity object" or one could use "string" to store PEM cert chain which is slightly easier to differentiate from DER encoded X.509 Certificate.

With Certificate mode with EST, the LwM2M Bootstrap Server only writes to resources "Security Mode" (/0/n/2) and "Server Public Key" (/0/n/4). It does not interact with the resources "Public Key or Identity" (/0/n/3) or "Secret Key" (/0/n0/5). So I cannot see any issue.

Be careful to distinguish the LwM2M Object Resources which are an interface between the Server and the Client, and the actual storage of the values which is implementation dependant.

Regards,

**Comment by vesajaaskelainen** [comment]
Hi @dnav,

With Security Mode 2.

Certificate Usage is for client to analyze how Server Public Key (Certificate) is used by Client Certificate to verify that server where connection is being made is correct.

We are missing possibility In Security Mode 2 to provide intermediate CA for the client.

Thanks,
Vesa Jääskeläinen

**Comment by sbernard31** [comment]
Maybe my fault because, at the beginning I mixed up server certificate and client certificate resource. :grimacing: 

But my initial point was only about client certificate. (so `Public Key or Identity` resource /0/?/3)
So as I understand the specification `Certificate Usage` (/0/?/15) is out of topic as this is about server certificate usage (`Server Public Key` /0/?/4).

What I understand : for now, using Security Mode 2, there is no way to use intermediate CA. Is it correct ?
The only way to use intermediate CA for now is with EST, right ?

**Comment by hannestschofenig** [comment]
You guys raise very good points in this discussion. 

I believe you stumbled over two issues: 

First, there is an inconsistency in the specification because the object definition says that the Certificate Usage Resource is applicable only to the Server Public Key Resource whereas the TRANSPORT spec explains that it is also applied to the Public Key and Identity Resource. The intention was to have the Certificate Usage Resource apply only to the Server Public Key Resource. We need to fix this issue. 

Second, we leave the format for the certificate and certificate chain unspecified in the Public Key and Identity Resource. (For the PSK and the raw public key encoding we are explicit though.) The two formats used today in practice are PKCS#7 and PEM. We could in a future version of the LwM2M specification add other formats, if those two do not fit your needs. We could, however, make it explicit in the spec that those are the two formats to use.

**Comment by sbernard31** [comment]
> Second, we leave the format for the certificate and certificate chain unspecified in the Public Key and Identity Resource. (For the PSK and the raw public key encoding we are explicit though.) The two formats used today in practice are PKCS#7 and PEM.

So, it's OK to store PEM certificate chain in /0/?/3 resource ? If yes, this is good news.

> We could in a future version of the LwM2M specification add other formats, if those two do not fit your needs. 

I think those both format (pkcs7/der and PEM) are enough. At least for us. (@vesajaaskelainen  could you confirm ?)

> We could, however, make it explicit in the spec that those are the two formats to use.

I think this will be a good addition.

**Comment by vesajaaskelainen** [comment]
> > Second, we leave the format for the certificate and certificate chain unspecified in the Public Key and Identity Resource. (For the PSK and the raw public key encoding we are explicit though.) The two formats used today in practice are PKCS#7 and PEM.
> 
> So, it's OK to store PEM certificate chain in /0/?/3 resource ? If yes, this is good news.
> 
> > We could in a future version of the LwM2M specification add other formats, if those two do not fit your needs.
> 
> I think those both format (pkcs7/der and PEM) are enough. At least for us. (@vesajaaskelainen could you confirm ?)
> 
> > We could, however, make it explicit in the spec that those are the two formats to use.
> 
> I think this will be a good addition.

Sorry for slow response -- I was in a vacation last week.

PKCS#7 container as DER and PEM (with chain) would do fine. PEM should be easily automatically detectable (vs. DER) to determine which path to go. I believe in the spec wording says there should be X.509 certificate encoded as DER:
```
If the Certificate Usage Resource is missing this Resource MUST be used to store the X.509 certificate of the TLS/DTLS client in a DER encoded binary format.
```

I would say that would be commonly understood as X.509 DER and not PKCS#7 DER container. eg. output of following:

```openssl x509 -in mycert.pem -inform PEM -out mycert.der -outform DER```

And this format (as far as I know) cannot really carry chain. On by convention PEM's could be chained in same file/blob.

In EST we have PKCS#7 container for CA certs and certificates. Only shame with EST is that specification requires one to fetch CA certificates and chain certificates with /cacerts and then re-construct the chain and then that re-constructed chain would then be stored in security object/public key (`Public Key or Identity` field). Even thou the simple enroll format would allow one to carry full chain.

It might be a good idea to indicate that in specification so that implementors test that all supported cases work nicely.

EST side of things is also a bit light in testing specifications which could create interoperability issues.

**Comment by sbernard31** [comment]
@vesajaaskelainen,  not exacly linked to this but : 
Reading https://tools.ietf.org/html/rfc6698#section-2.1.1, it seems that **certificate** OR **public key** could be used for checking.
If we want to support both,   "Server Public Key" could be able to store either a "certificate" or "public key".
To do that we need to define format to use : 
I suppose PKCS#7 DER \[RFC2315\] for certificate, (as we need to store only 1 certificate)
and SubjectPublicKeyInfo structure, as described in \[RFC7250\] for public key (like RPK mode to be consistent)
BUT I asked myself : 
**is it easy for implementer to know if "server public key" resource contain PKCS#7 or SubjectPublicKeyInfo ? I**
(I mean like it is easy to know if resource contains DER OR PEM)
Do you have any input about this ?

**Comment by hannestschofenig** [comment]
IMHO it is fairly easy to distinguish the PKCS#7 encoded certificate from the SubjectPublicKeyInfo encoded RPK because both is DER encoded and by parsing the DER structure you can see what it is.

**Comment by hannestschofenig** [comment]
This issue has been resolved by LwM2M v1.2: 
http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/

**Comment by sbernard31** [comment]
@hannestschofenig, this has been resolved by specifying clearly that `Public Key or Identity` is 1 certificate in DER or PEM encoding. 

So could you confirm that for LWM2M 1.2 (and lower)  when using **Certificate Mode**, the supported use-cases are only : 
 - Client Self-Signed Certificate,
 - Root CA --> Client Certificate.
 
The use-cases "Root CA"-> ... -> "intermediate CA" -> .... -> "client Certificate" is not usable as this is not possible to provide a Certificate Chain at bootstrap time ? 
 
Correct ?

**Comment by hannestschofenig** [comment]
To answer your question: when using a PEM encoding you can chain various certificates together. This would look like:

-----BEGIN CERTIFICATE-----
.... end entity certificate certificate...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
.... intermediate CA cert...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
.... root cert...
-----END CERTIFICATE-----

**Comment by sbernard31** [comment]
I know that PEM can be used to store 1 certificate or severals (e.g. for certificate chains) but the specification says : 

> The "Public Key or Identity" Resource MUST be used to store **the X.509 certificate** of the TLS/DTLS client. DER encoding [RFC5280] MUST be supported by the LwM2M Client and LwM2M Bootstrap-Server. PEM encoding [RFC7468] MAY be supported by the LwM2M Client and LwM2M Bootstrap-Server.

The wording seems to mean that this is only 1 certificate and so not a certificates chain.

I vaguely remember that @dnav wanted to limit to 1 certificate. I think this was in the private repo of the spec but I haven't access anymore. (I'm really not sure about this :sweat_smile:)

But now your answer makes me think that it's OK to use certificates chain, so I'm a bit confused.

**Comment by sbernard31** [comment]
By the way, thx a lot @hannestschofenig  to take time to look at all those issues.

**Comment by hannestschofenig** [comment]
The bugfix release of the LwM2M specification will contain a clarification in the text.
