### ISSUE TITLE
No multipurpose mandatory content format in LWM2M v1.1

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#514]
Not sure my title is very clear :sweat_smile:, I will try to be better with my description.

In **LWM2M v1.0**, TLV was a format usable for all kind of value. (object, object instance, single resource, multi resource ... ) and was mandatory for both side : client and server. That's was a really good default value which allow good interoperability easily.

In **LWM2M v1.1**, all format are mandatory at server side but at client side : 
- TLV is deprecated,
- TEXT & OPAQUE is mandatory but does not support "object" or "object instance",
-  it SHOULD support at least one of SenML CBOR or SenML JSON data formats but server does not know which one exactly,
- optional content format could be present in `Register request` but this is just a "MAY" not a "MUST".

_(source : [lwm2m-v1.1-core§7.4 Data-Formats-for-Transferring-Resource-Information](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#7-4-0-74-Data-Formats-for-Transferring-Resource-Information))_

It is still possible to try with a format and retry with another but my feeling is a common mandatory multi-purpose (which is able to target object, object instance, single resource, multi resource or anything) content format would be a good idea for easy interoperability. 

(This remarks also concerns LWM2M v1.2 : [lwm2m-v1.2-core§7.4 Data-Formats-for-Transferring-Resource-Information](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#7-4-0-74-Data-Formats-for-Transferring-Resource-Information))

**Comment by hannestschofenig** [comment]
Let me describe the intent of v1.1 and v1.2. 

In v1.0, TLV was the mandatory format. In v1.1 and v1.2 we added more formats. TLV has not been depreciated. Different formats have different properties and preferences change over time. TLV is, however, still a perfectly fine format to use. 

To accomplish interoperability we wanted to demand the server to support all whereas the client can pick. This makes sense for an environment where the client is constrained and the server typically isn't. 

LwM2M v1.1 and v1.2 have to be backwards compatible. Hence, we could not drop any of the formats. Currently, the v1.1.1 spec only says that the TLV SHOULD NOT be used. But, if there is no other choice then it has to be used. 

So, if a v1.0 client comes along with the TLV format and contacts a server that supports v1.0 and v1.1 then it will work fine because the server has to support TLV. 

If a v1.1 client uses the TLV format then it will also work because the v1.1 server will have to implement the v1.1 format. 

If a v1.1 client decides to use a format other than TLV, the v1.1 server will also be able to understand it since it has to implement everything.

**Comment by hannestschofenig** [comment]
FWIW I would implement TLV in a v1.1 and a v1.2 client when prior knowledge of the deployment environment is unknown.

**Comment by sbernard31** [comment]
I agree that a client and a server will always be able to exchange data because a server MUST support all format.

But it's not exactly my point. I would rather bring to your attention that there no "mandatory way" which allow a server to select a format which could work for sure for the targeted device in LWM2M v1.1.

There was a mandatory way in LWM2M 1.0 : use TLV.
There was optional way in LWM2M 1.1 `ct` option in register request.

But I think it would be better for the standard to have mandatory way : 
- either by selecting a multi purpose mandatory format at client side.
- or make the `ct` option mandatory. 

Does it make sense ?

**Comment by sbernard31** [comment]
Just one remark in LWM2M 1.0, TLV can be used for all feature. (One exception historical data) So it was a really good choice.

For LWM2M 1.1, TLV can not be used for composite operation so maybe a less good choice. SENML_JSON or SENML_CBOR seems to be the only format which can be used for any feature. So probably both of them are good candidate for a common mandatory multi purpose content format.

**Comment by hannestschofenig** [comment]
We need to think about whether we can make ct mandatory. ct is defined in the CoAP RFC and added to CoRE Link Format. The CoRE Link Format has not been mentioned as mandatory to implement for clients in the v1.0 specification. 

An additional consideration is that the bootstrap interface uses a different parameter "Preferred Content Format" for indicating the supported content formats, which is marked as optional in the spec. 

As you say, we could indicate that the TLV for the LwM2M client in v1.1 is mandatory to implement, unless a profile of the specification defines otherwise. Then, a client implementation could add another parameter on top of it. 

The latter approach looks a bit more promising to me.

**Comment by sbernard31** [comment]
> An additional consideration is that the bootstrap interface uses a different parameter "Preferred Content Format" for indicating the supported content formats, which is marked as optional in the spec.

An out of topic remarks about that LWM2M server and LWM2M bootstrap server  needs same kind of information : 
- endpoint name
- supported content format
- lwm2m version
- object supported and object version. 

Ideally the register request and bootstrap request should be more similar

**Comment by mkgillmore** [comment]
Group agrees that this issue is resolved and can be closed 10/31/2023

**Comment by sbernard31** [comment]
@mkgillmore can you elaborate ?

Resolved by what ? and in which version of the specification ?
