### ISSUE TITLE
More detailed explanation about LWM2M Gateway ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#518]
I see there is a new concept introduce in LWM2M 1.2 :[ LWM2M Gateway.](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#1-1-0-11-LwM2M-version-12)

> Support for LwM2M gateway functionality; this allows non-LwM2M IoT devices as well as LwM2M devices behind a gateway to be connected to the LwM2M ecosystem and to manage those devices remotely.

but I can find details explanation and so I'm not sure to understand how it works. The only thing I found is object descriptions : 
- [LwM2M-Gateway](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#13-12-0-E12-LwM2M-Object-LwM2M-Gateway)
- [LwM2M-Gateway-Routing](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#13-13-0-E13-LwM2M-Object-LwM2M-Gateway-Routing)

I looked at this because of this leshan question : https://github.com/eclipse/leshan/issues/974

**Comment by hannestschofenig** [comment]
We actually made a mistake in the publication of the specification and did not include the description on how to use the gateway-related objects. We will obviously publish them as soon as possible. In the interim we will make the missing text available on the OMA website. I will discuss the procedures with the group at the weekly conference call.

**Comment by jpradocueva** [comment]
@hannestschofenig keep us in the loop if there is something to rectify in the current publication. Thanks

**Comment by jbuckAI** [comment]
Hi! Any chance that link for gateway usage is live?

**Comment by lodup29** [comment]
Any news on this? I still can’t find anything on the OMA website describing how those 2 objects shall be used.

Assuming that the end device is a LwM2M client, my best guess is that a gateway behaves as a server on one side, accepting registrations from end devices, then turns back and establish a new registration, specific to each end device, with its own server where the registration ID is build using a prefix (25/*/1, RW, by default could be the registration ID of the gateway itself) and the end device ID (25/*/0, registration ID of the end device when the later is a LwM2M client).

So, the added value of a Gateway over a simple proxy (LwM2M only context) would be to have a formal and automatic mean to identify the site (the ID of the gateway) of the end device through its connexion ID?

In this context, the gateway object would only be used by the main server to change the prefix of the registration ID for an end device, or for information purposes only. Unless the prefix extraction is performed by the server, the later wouldn’t care about the fact that a gateway is involved.

If the end device is not a LwM2M client, then I guess that the device ID wound typically rather be fixed by the configuration of the gateway itself.

But I can hardly put together the pieces of the Gateway Routing object. Basically, it’s a table where each entry combines an Object ID (referred to as the “source of the mapping”) and mapping information which basically points to a single resource (referred to as the “destination of the mapping”) using the Corelnk type (ex.: <3303/0/9002>;rt=“oma.lwm2m”) .
Referencing an entry from the routing table is optional for an instance (device) of the Gateway object, but if it does, it can only reference a single entry (Objlnk type cannot reference multiple instances).

I can’t think of a context where it would make sense to publish the mapping info of at most one object ID per device and have that object ID associated with a single resource.

**Comment by sbernard31** [comment]
@lodup29, @jbuckAI the specification is released at :  http://www.openmobilealliance.org/release/LwM2M_Gateway/

**Comment by sag-eweingaertner** [comment]
@sbernard31 Out of curiosity, do you know about any activity of somebody implementing Gateway support in Leshan officially? Or is this currently on your agenda?

A a customer of ours informed us a couple of weeks ago that they hacked Gateway support into the Leshan code base, simply with the goal of figuring out if it can be done. It turned out to be possible by hacking around the limitations of the Link class (number of path elements, string prefixes required).

We have encouraged them to push it to a branch here, but I'd also like to know if there is possibly somebody else also working on it already. From our perspective, Gateway is a highly anticipated feature...

**Comment by sbernard31** [comment]
>  do you know about any activity of somebody implementing Gateway support in Leshan officially?

AFIAK, nobody is working on this currently. 

> Or is this currently on your agenda?

If I remember well this is a LWM2M v1.2  feature, right? 
And unfortunately we are sill focus on implementing LWM2M 1.1.  : https://github.com/eclipse/leshan/issues/1235
Sometime, we feel we are not fast enough :disappointed: 

> A a customer of ours informed us a couple of weeks ago that they hacked Gateway support into the Leshan code base somehow, simply with the goal of figuring out if it can be done. It turned out to be possible by hacking around the limitations of the Link class (number of path elements, string prefixes required) in combination with some other hacky ways. Certainly not something to directly use, but it was great to see it can be done.

Yep, great to know that.
We recently refactor a lot about  `Link` in Leshan the current development branch (`master` used to develop the v2.0.0 of Leshan) I don't know if this will make the change easier or harder :grimacing:. Or maybe you are more talking about `LwM2mPath` class ? 

> We have encouraged them to push it to a branch here, 

Yes this is good idea. Even if this will probably not be integrated soon, this could be used as base for future development and/or for discussion and/or for other users who can not wait for a version of Leshan targeting LWM2M v1.2.

>  From our perspective, Gateway is a highly anticipated feature...

OK I will add this feature to the list  at : https://github.com/eclipse/leshan/issues/1235

@sag-eweingaertner, thx for sharing this with us :pray:

**Comment by hannestschofenig** [comment]
Since there are no further questions about the gateway specification I will close this issue.
