### ISSUE TITLE
Limited variety of keys in the OSCORE object

### ISSUE THREAD

**Issue by panekk** [OpenMobileAlliance/OMA_LwM2M_for_Developers#521]
Hello,

The new definition of LwM2M OSCORE object has been released (OMA-TS-LightweightM2M_Core-V1_2-20201110-A), but resources 0, 1, 2, 5 and 6 still have the String type. Using Opaque type will allow to represent more possible values of the resources. If we take 128-bit Master Secret as an example, using only printable characters allows to represent only about 0,000013% (depends on if we treat '\t', '\n' etc. as a printable character, but this number is pretty small anyway) of all possible combinations of 128 bits.

Best regards,
Kamil

**Comment by rikard-sics** [comment]
I am currently working on integrating support for OSCORE into the [Leshan LWM2M framework](https://www.eclipse.org/leshan/).

I agree with your point. It would make sense to change the OSCORE object so that all resources that currently have String type instead use Opaque. Fundamentally the values like master secret for example are not really strings but arbitrary binary data.

**Comment by akeranen** [comment]
Looking at the resource description, indeed it's not very clear how is the key encoded. It says nothing about printable characters and string type is simply a UTF-8 string so I would expect you can encode majority of possible keys with that? For JSON you have [escape rules](https://datatracker.ietf.org/doc/html/rfc8259#section-8) where needed and with CBOR you can use the UTF8 set as such. That said, I'm not against changing this to Opaque but rather exploring first are there ways we can clarify this without changing the object.

**Comment by rikard-sics** [comment]
One potential way could have been to let the user input the key as hex, but then store it as a UTF8 string. Unfortunately a lot of byte combinations will result in invalid UTF8 strings (e.g. 0xAABB).

Another alternative can be to let the user input the key as hex and store it as as string of the hex bytes. So for instance if a user wants as Master Secret 0xAABB, what is stored is the string "AABB". That would allow any possible values for e.g. Master Secret, not limiting things because of storing them as strings.

So one aspect can be how the keys are entered (as strings or hex) and another how they are stored. If they are input as strings that certainly limits the options, as some characters simply cannot be entered.

Personally I would be partial to the solution of changing the storage to opaque, as fundamentally these values are not strings but arbitrary sequences of bytes. So that way of storing them feels more consistent. It is also consistent with then letting them be input as hex bytes, or as a string which gets converted to UTF8 (e.g. Tëst->54c3ab7374).

**Comment by sbernard31** [comment]
It seems there is a [LWM2M OSCORE object](https://md2html-tool.com/docs/OpenMobileAlliance/LwM2M/master/c47850f/SUP/objects-lwm2m/master/21.html) version 2.0 where OPAQUE is used instead of STRING.

But this version is not available in [LWM2M Registry](See https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/21.xml#L68), @akeranen do you know when this will be released ?

**Comment by jmudge** [comment]
@sbernard31 LWM2M OSCORE V2.0 will be released following its approval by the OMA Board of Directors.

**Comment by jpradocueva** [comment]
@sbernard31 the next Board of Directors is Monday, Feb 28th. The LwM2M OSCORE v2.0 will be available within 24 hours after the approval.

**Comment by sbernard31** [comment]
@jmudge @jpradocueva thanks you very much for the prompt answer :pray: 

We are not sure but we are thinking about skipping previous version of OSCORE object in Leshan. :thinking:

**Comment by mkgillmore** [comment]
Resolved in 1.2x release
