### ISSUE TITLE
Object composition / inheritance

### ISSUE THREAD

**Issue by MaikVermeulen** [OpenMobileAlliance/OMA_LwM2M_for_Developers#530]
For a few products, we have configurations with a lot of overlap, but not entirely.
It would be great if we could split the overlapping parts into separate modular objects, so that their re-use and combination becomes easier.

Is it possible to then have 1 object that links to / is composed out of those modular objects?
That way pushing a configuration is a more coherent action.

We have read about ObjLink but we're hoping to learn from how this problem has been tackled by others!

**Comment by hannestschofenig** [comment]
There are two options that come to my mind: 

* Using re-usable resources, 
* Using the object link


We have a number of re-usable resources already and hence it is easy to use them across several objects.
The object link makes sense if there is indeed some form of hierarchy where one object is a composite of others. 

You might also be able to define a better data model so that there is not much duplication. I cannot give detailed recommendations since I don't know how your objects look like.

**Comment by hannestschofenig** [comment]
> Is it possible to then have 1 object that links to / is composed out of those modular objects?

Yes. That is what the object link has been designed for.
