### ISSUE TITLE
How can send updates of an object or updates of the instances of an object?

### ISSUE THREAD

**Issue by ce237** [OpenMobileAlliance/OMA_LwM2M_for_Developers#533]
Hi,

i am trying to send updates of an object or updates of the instances of an object, with out actually waiting for the server to request for the update.

Is it possible in the first place to do that with lwm2m? When yes, may someone suggest to me how i may go about it?

Best regards,

Cedric

**Comment by sbernard31** [comment]
> with out actually waiting for the server to request for the update.

That seems obvious to me that you don't want to use **Read** Request as this is fully initiated by the server.
This is less clear to me if an **Observe** Request could be acceptable to you because the observation is initiated by the server but once the observation is established, notifications are sent at the client initiative.
See http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-4-1-0-641-Observe-Operation

Anyway, since LWM2M v1.1, there is a **Send Operation** which is totally client initiated. 
See :  http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-4-6-0-646-Send-Operation

**Comment by ce237** [comment]
Hello thanks for your reply.

I want the request to be totally client initiated.

By just out of curiosity, do you know how i may implement this Send operation in C?

**Comment by sbernard31** [comment]
> By just out of curiosity, do you know how i may implement this Send operation in C?

I'm not sure what could be a good answer to this question. :confused: 

But there are some open source implementation of LWM2M in C :  
 - https://github.com/eclipse/wakaama
 - https://github.com/AVSystem/Anjay
(I don't know if Send operation is implemented)

**Comment by ce237** [comment]
Hi,

thanks for your reply once again.

but do you have any idea of how, i may incorporate a client initiated way of sending data to the server without having to wait for a request from the server using LWM2M v1.0.

**Comment by mkgillmore** [comment]
Group agrees that this issue is resolved and can be closed 10/31/2023
