### ISSUE TITLE
v1.2 Transport MQTT operation number clash

### ISSUE THREAD

**Issue by cwest-tde** [OpenMobileAlliance/OMA_LwM2M_for_Developers#543]
From the document OMA-TS-LightweightM2M_Transport-V1_2-20201110-A.pdf.

In section '8.3 Interface Mappings' for MQTT there are some oddities with the number of the operations as 'Bootstrap-Pack-Request(6)' and 'Register (6)' look to use the same number as I would expect them to be different numbers could you please clarify if this is correct?

Thanks,
Chris

**Comment by hannestschofenig** [comment]
Chris, you are right. The numbering got messed up when we made some last minute changes :-(

We will discuss this topic at our next group call next Tuesday and we will find a resolution

**Comment by hannestschofenig** [comment]
Conclusion from the discussion in the group: There is no problem since the Bootstrap-Pack-Request operation would be published on the bootstrap dedicated topic (lwm2m/bs/<ENDPOINT>) whereas the Register operation would be published on the registration dedicated topic (lwm2m/rd/<ENDPOINT>). 

Still, the numbering scheme could have been better aligned. Changing the values at this point in time would, however, create a backwards compatibility-breaking change.
