### ISSUE TITLE
Support for TLS_PSK_WITH_AES_128_CBC_SHA256 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LwM2M_for_Developers#6]
TS, section 7.1.1 Pre-Shared Keys.
According to OMA LwM2M `TLS_PSK_WITH_AES_128_CBC_SHA256` is mandatory. However in CoAP [RFC7252], only   `TLS_PSK_WITH_AES_128_CCM_8` is mandatory. And the same in the DICE profile.

Also in TS, section 7.1 indicates:
`2) Bootstrapping with a temporary, low-entropy pre-shared secret (such as a PIN, password and private serial number) using the cipher-suite TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256, as defined in RFC5489.`
IETF recommends do not use `TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256`, (DICE and UTA Working Group). 

It is suggested that `TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256` should be removed from the specifications.

**Comment by BillBennett** [comment]
It's worth pointing out that none of the CCM_8 ciphers are implemented yet in the major TLS libraries. For quick adoption it may be a good idea to specify the 2nd cipher as something that is already available.

**Comment by ThGarnier** [comment]
Yes : regarding removing TLS_PSK_WITH_AES_128_CBC_SHA256, opinions are divided.
For sure not only one cipher suite must be supported from the server side (so 2 in our case) . 
NB: TLS_PSK_WITH_AES_128_CBC_SHA256 is also supported by oneM2M.
If there is a better choice to (or a strong opposition to ) TLS_PSK_WITH_AES_128_CBC_SHA256 please advise. At that time LWM2M TS  stays as it is on that point.

**Comment by jvermillard** [comment]
AES-CBC will be expelled for TLS 1.3 and so DTLS 1.3
I think it's fair to offer an alternative to CCM,
AES-CGM and ChaCha20-Poly1305 AEAD ciphers are better alternatives, without known flaw like AES-CBC

AES-CGM is now largely used for web-browsers and Chacha2020-Ploy1305 for smartphones

**Comment by BillBennett** [comment]
I think you mean AES-GCM? I agree that it's implemented in all the major TLS libraries and would solve the problem.
However I understand it has catastrophic consequences for nonce reuse - I'm concerned that it may be difficult to implement securely, particularly in PSK mode. If chosen the specification should provide guidance on generating the nonce in a way that doesn't rely on the device clock or frequent writes to flash.

Chacha20 doesn't have good support, so it's not much better than AES-CCM. I suspect it will take even longer to implement since DTLS 1.0 & 1.2 completely ban stream ciphers.

**Comment by hannestschofenig** [comment]
This is my personal opinion as a co-author of the "DTLS/TLS Profiles for IoT" draft. 

jpradocueva is correct that the mandatory-to-implement ciphersuite has to be TLS_PSK_WITH_AES_128_CCM_8 since this would be inline with the CoAP RFC and also with http://tools.ietf.org/html/draft-ietf-dice-profile-14 

In the IETF we discussed the possibility to use CCM instead of the CCM_8 and the conclusion has been documented here: http://www.ietf.org/mail-archive/web/dtls-iot/current/msg00643.html 

Also the question about using ChaCha20 has been discussed in the IETF and here is the solution: http://www.ietf.org/mail-archive/web/dtls-iot/current/msg00650.html 

A discussion between AES-CCM and AES-GCM has been discussed and the resolution can be found here: http://trac.tools.ietf.org/wg/dice/trac/ticket/19

Best regards, 
Hannes Tschofenig

**Comment by hannestschofenig** [comment]
As a follow-up: I will investigate whether there are problems with the  TLS_PSK_WITH_AES_128_CBC_SHA256. 

If there are no known security vulnerabilities with  TLS_PSK_WITH_AES_128_CBC_SHA256 then it will be hard to remove the algorithm from the mandatory-to-implement ciphersuites since companies have implemented their products using this ciphersuite. 

Nevertheless, I believe it would have been better to either only select one algorithm as mandatory-to-implement or to pick two algorithms that are very different in their design so that there is a backup once one algorithm gets broken.

**Comment by hannestschofenig** [comment]
My co-worker Manuel provided the following input to the discussion:

"Security wise, the usual issues with CBC: (1) prior to TLS 1.1 IV selection is broken (solution: use TLS 1.1 or higher, known work-around for earlier version: record splitting), and (2) implementing authenticated decryption (checking padding and mac) without any side channel is pretty hard (see Lucky 13 and its numerous variants) - known fix: the encrypt-then-mac extension (RFC 7366).

On a more practical note, CCM_8 has lower overhead. The overhead is 53 bytes for CBC-SHA256 vs 21 bytes for CCM-8 (just checked). That’s a full 32 bytes saved for each packet
"

So, it seems that we would have to require implementation of RFC 7366 with TLS_PSK_WITH_AES_128_CBC_SHA256 to ensure proper security.

**Comment by BillBennett** [comment]
Quick survey shows OpenSSL still doesn't implement CCM for (D)TLS.

I think that mandating two ciphers for the non-constrained server-side is not really a problem. I don't have input on what the 2nd cipher suite should be, as long as it's something with widespread support currently.

The key here is that not all clients using LWM2M will be constrained and many of those already deployed will already have full TLS libraries. It seems like mandating something that's not in those libraries is going to lead to them including 2 separate implementations, which means more to maintain and potentially more exploits.

Also as mentioned above, I do think that nonce reuse is something that's likely to be easy for implementers to screw up on real-world devices (i.e. no RTC, write-limited flash). An appendix of info on how to do that right might be a good thing to include.

**Comment by jvermillard** [comment]
OpenSSL 1.1 is just released and support CCM8 (I'm testing the beta for few month now).

OpenSSL 1.0 AES CBC  (which you probably use) doesn't implement encrypt then mac extension, you are not safe at all.

I don't mind using CBC but you need to use https://tools.ietf.org/html/rfc7366 which is now mentioned in the last LWM2M draft and is not supported in OpenSSL 1.0, but in 1.1 .

OpenSSL 1.1, Mbed TLS, GnuTLS and WolfSSL are all supporting CCM8 now.

So I don't see how with openSSL 1.0 you can implement something safe, and I don't think the LWM2M spec should allow that (CBC without RFC7366).

**Comment by BillBennett** [comment]
Thanks for the info. Will have to try it out.
Couldn't find anything about it on the lists and in 1.0.2 it was available for their EVP interface but not TLS.

**Comment by jvermillard** [comment]
on my version of openssl 1.1:
./openssl ciphers aPSK
DHE-PSK-AES256-GCM-SHA384:DHE-PSK-CHACHA20-POLY1305:ECDHE-PSK-CHACHA20-POLY1305:**DHE-PSK-AES256-CCM8**:DHE-PSK-AES256-CCM:PSK-AES256-GCM-SHA384:PSK-CHACHA20-POLY1305:**PSK-AES256-CCM8**:PSK-AES256-CCM:DHE-PSK-AES128-GCM-SHA256:**DHE-PSK-AES128-CCM8**:DHE-PSK-AES128-CCM:PSK-AES128-GCM-SHA256:**PSK-AES128-CCM8**:PSK-AES128-CCM:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA:ECDHE-PSK-CAMELLIA256-SHA384:DHE-PSK-CAMELLIA256-SHA384:PSK-AES256-CBC-SHA384:PSK-AES256-CBC-SHA:PSK-CAMELLIA256-SHA384:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA:ECDHE-PSK-CAMELLIA128-SHA256:DHE-PSK-CAMELLIA128-SHA256:PSK-AES128-CBC-SHA256:PSK-AES128-CBC-SHA:PSK-CAMELLIA128-SHA256:ECDHE-PSK-3DES-EDE-CBC-SHA:DHE-PSK-3DES-EDE-CBC-SHA:PSK-3DES-EDE-CBC-SHA:ECDHE-PSK-NULL-SHA384:ECDHE-PSK-NULL-SHA256:ECDHE-PSK-NULL-SHA:DHE-PSK-NULL-SHA384:DHE-PSK-NULL-SHA256:DHE-PSK-NULL-SHA:PSK-NULL-SHA384:PSK-NULL-SHA256:PSK-NULL-SHA

**Comment by boaks** [comment]
From above (Hannes):

`So, it seems that we would have to require implementation of RFC 7366 with TLS_PSK_WITH_AES_128_CBC_SHA256 to ensure proper security.`

I'm not sure and no encryption expert:

Do you mean **TLS_PSK_WITH_AES_128_CCM_8** has lower securtiy than **TLS_PSK_WITH_AES_128_CBC_SHA256** ?
Or do you mean "to make **TLS_PSK_WITH_AES_128_CBC_SHA256** secure", RFC 736 must be implemented?

**Comment by hannestschofenig** [comment]
> "to make TLS_PSK_WITH_AES_128_CBC_SHA256 secure", RFC 7366 must be implemented

Correct. 

AES_128_CCM_8 and AES_128_CBC_SHA256 are different in two respects, namely
 * CCM is an AEAD mode that is superior to the older CBC mode for the previously discussed security issues. Here is a bit more info: https://tools.ietf.org/html/rfc5116 
 * CCM_8 also has a lower per-packet overhead due to the truncated authentication tag.

**Comment by boaks** [comment]
Thanks!

**Comment by hannestschofenig** [comment]
We discussed this issue at the OMA meeting in Paris today and the participants in the room agreed on the following way forward: 
 * We will keep the AES-128-CBC-SHA256 ciphersuite but make RFC 7366 a normative reference. 
 * We will add a note that the CBC-based ciphersuite will be depreciated in LWM2M version 1.1. 

This is inline with what has been proposed with the following CR: 
http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2016/OMA-DM-LightweightM2M-2016-0102-CR_ciphersuite.zip

**Comment by ThGarnier** [comment]
Includedin Oct16 TS => to be closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment this is included in October 2016
