### ISSUE TITLE
Observation lifetime and registration

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#71]
I can not find any information about that in the specification, but I suppose an observation is valid only for a particular registration ? I mean when a device do a `De-register` we can cancel all the associated observations (free the server resources) ? 
If I'm right, I think this should be explicitly explain in the specification.

**Comment by boaks** [comment]
I also think this should be explicitly defined.
Even more, I would also enjoy it, if the wanted behaviour of an "registration update" with a new ip-address would be defined.
(There are ideas/plans in the californium project, to extend/preserve an observation when the ip-address has changed. Not clarifying the specification also at that point may result in unexpected compatibilty problem using other CoAP layers, which didn't implement a "preserved observation".)

**Comment by jvermillard** [comment]
should be fixed by http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2016/OMA-DM-LightweightM2M-2016-0024R01-CR_Clarify_observation_lifetime_over_registrations.zip

**Comment by boaks** [comment]
No details about the wanted behaviour on registration update with new ip-address (or port)?

Is the behaviour of a ip-address (or port) change addressed/discussed in the observe RFC 7641?
If not, I would expect some (LWM2M server side) CoAP implementation failing because they don't know nor support this "extension".

**Comment by jvermillard** [comment]
I suppose the server can send registration again if needed (because he see the changing IP).
Should work on a resumed DTLS session.
But yeah it's a grey zone of the CoAP RFC and personally I would like to resend all the GET on registration updates because it can be costly in bandwidth

**Comment by boaks** [comment]
"I suppose the server can send registration again if needed (because he see the changing IP)."

A LWM2M client (the COAP server for that observe) may not able to detect an address change, if an "IPv4 NAT on the way" changes the mapping. This includes many scenarios, e.g. device behind a WAN router.

And, even if the device could detect such a change, you saying, that this requires a (re-) registration? Then the TS should change 5.3.2 Update to clarify, that a address change with pending observes must use 5.3.1 Register.

**Comment by boaks** [comment]
> "I suppose the server can send `registration` again if needed (because he see the changing IP)."

Or did you mean:

"I suppose the server can send an `observation request` again if needed (because he see the changing IP)."
?

**Comment by dnav** [comment]
This issue will be addressed in the next TS.
It will enforce that Observations are valid only for a registration.

Regards,
