### ISSUE TITLE
Several comments on behalf of ZHAW

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LwM2M_for_Developers#72]
Subject : OMA-TS-leightweightM2M-V1_0-20141126C

Details of the comments : Hello 

I have been going through the above specification in the course of writing a lecture for my IoT students and a couple of things have caught my notice.

Here they are in random order:

1.) page 57 - doesn't handle the mapping of Discovery operation to CoAP
2.) page 20 - second last paragraph should read &quot;example client of Appendix F):
3.) the example below this paragraph - should this not read &lt;/1/101&gt;, &lt;/1/102&gt;, &lt;/2/0&gt;, &lt;/2/1&gt;, &lt;/2/2&gt;, &lt;/2/3&gt;, &lt;/2/4&gt;, &lt;/3/0&gt;, &lt;/4/0&gt;, &lt;/5&gt;? (The reasoning for the &lt;/5&gt; is not explained anywhere
4.) Figure 9 if there is only one Device object is it even possible to create &lt;/3/1&gt; and &lt;/3/2&gt;? 
5.) the same as 4.) for Figure 20 Figure 25
6.) Figure 26 seems to be in a random position

**Comment by boaks** [comment]
Is there any reason to use "OMA-TS-leightweightM2M-V1_0-20141126C" instead of the most recent version "OMA-TS-LightweightM2M-V1_0-20150910-D"? I thought, that a lot of issues from the "Candidate" are solved in the "Draft".

1.) Table 20, (page 58?) shows the mapping for the discover.
      "GET Accept: application/link-format" is the short form of, 
      Coap GET request with Coap Option Accept (RFC7252, 5.10.4) set to "application/link-format".
     (With Accept the LWM2M client is told, if content (text/tlv) or meta information (link-format) is
      wanted).

3.) The difference of </o> and </o/i> is described in the a few lines above. 
     The </o> is used, if the device supports the object but currently no instance is created,
     The other <o/i> indicates, that instances are already created. 
     May be changing
     "(for the example client of Appendix E)" into 
     "(for the example client of Appendix E, 2 server instances "/1/...", 4 access controls instances
     "/2/...", 1 device instance "/3/0", 1 connectivity monitor instance "/4/0" and no firmware update
     instance "/5"). explains ot better.

4.) Currently LWM2M device is documented as "single instance" (E.4.), so it's not possible to create
     more instance of the LWM2M object on one LWM2M client device.

**Comment by MarchBrown** [comment]
C was the version downloadable from the website - I assumed it was the latest version

1,) so it is but since all the other mappings are described in a line or paragraph I thought it odd that Discover should be left unexplained

3.) The line on page 20 referring to the example in Appendix F reads </1/101>, </1/102>, </2/0>, </2/1>, </2/2>, </3/0>, </4/0>, </5>
The objects in the example in Appendix F are actually </1/101>, </1/102>, </2/0>, </2/1>, </2/2>, </2/3>, </2/4>, </3/0>, </4/0>. In other words there are some instantiated objects missing on page 20 (at least according to my understanding). 

It would have been more clear if it explained somewhere (for instance in Appendix F) that object </5> was supported by the device but not instantiated. 

4.) precisely - its not possible to actually do it but the example sequence diagrams (Fig 9, 20 and 25) all show the use of </3/1> - these should be corrected

Best H.

**Comment by jpradocueva** [comment]
In answer to:
***"Is there any reason to use "OMA-TS-leightweightM2M-V1_0-20141126C" instead of the most recent version "OMA-TS-LightweightM2M-V1_0-20150910-D"? I thought, that a lot of issues from the "Candidate" are solved in the "Draft"."***

If you have access to "OMA-TS-LightweightM2M-V1_0-20150910-D", then this is the one that you should use. The difference is that the later is still in Draft; (-D). However it supersedes "OMA-TS-leightweightM2M-V1_0-20141126C". The Working Group is still applying Change Requests based on the list of issues listed in these pages. I will request the Working Group to send the latest baseline to be approved as Candidate ; (-C). Sometimes, the Working Groups prefer to keep it as Draft in order to apply all the Change Requests before asking for Approval.

**Comment by jpradocueva** [comment]
@MarchBrown & @boaks 

OMA-TS-LightweightM2M-V1_0-20150910-D is the latest available baseline. It is in Draft (-D). Which means the Working Group has not release a public version based on this baseline. The latest Candidate and therefore public version is OMA-TS-leightweightM2M-V1_0-20141126C.
I will encourage the Working Group to send the latest Draft baseline for approval, so you will have the latest baseline as Candidate (public) with all the latest changes.

**Comment by david-antliff-imgtec** [comment]
@jpradocueva All the drafts seem to be public now (although maybe not at the time you replied):

http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/Permanent_documents/

**Comment by ThGarnier** [comment]
After reviewing and according to my knowledge, all the points above are covered at least in  the TS1.0 20160407. So this issue will be closed. IF one aspect is notr covered, please reopen a new issue; once again with the sanity-rule of one question per issue  :-) . It helps for having a clear answer  :-)

**Comment by Megan-OMA** [comment]
Issue closing per Thierry's latest comment.
