### ISSUE TITLE
Server Public Key resource(4) of Security object (0) should not be mandatory.

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#77]
The `Server Public Key` resource(4) of `Security object` (0) is mandatory, but the resource is not needed when we use PSK mode.

**Comment by sbernard31** [comment]
In fact this is also true for `Public Key/Identity` resource(3), `Server Public Key` resource(4) and `Secret Key` resource (5) whe we use the NoSec mode.

**Comment by alex-ellwein** [comment]
@sbernard31 
in my understanding of the spec, the following does NOT imply that a _mandatory_ resource should have a concrete value. Correct me please if i am wrong.

> Mandatory: if this field is “Mandatory”, then the LWM2M Client MUST support this Object. If this field is “Optional”, then the LWM2M Client SHOULD support this Object.

**Comment by sbernard31** [comment]
@alex-ellwein   @boaks you point a real question, what  means "support" ? does it mean : 
  1) must be implemented but no actual value is required or
  2) must be implemented and actual value is required

if this is 1) how do you materialize an implemented resource with no value ?  Does it mean that all  resources are nullable ? if this is case how to we make difference between an empty string and a null string in text and tlv format ?  
Currently in leshan, we consider ressources are not nullable. I mean no value == resource NOT_FOUND.
So there is an other another point to clarify : nullablility of resources ? 

The § 7.3.2.3 seems match with the 2) solution :
_"For the “Create” operation, the LWM2M Client MUST perform the operation on the Object Instance only if all
the mandatory Resources are specified in the “New Value” parameter (see Section 5.4.6). If all the mandatory
Resources are not specified, the LWM2M Client MUST send an “Bad Request” error code to the LWM2M
Server."_

**Comment by boaks** [comment]
The point is:
If mandatory means "actual value is required", 
 would guess, that the objects need to be (re-)checked to match that!

E.g. "Location" defines "latitude", "longitude" and "time" as mandatory. So what should be used when the devices doesn't have a valid position?

**Comment by ThGarnier** [comment]
The initial understanding of sbernard31 :-) is right : In  LWM2M spirit,  having a resource  mandatory  means, the Server will be sure this resource is present in the Client. That's why most of the resources are just optional. But in no case, mandatory (or optional) type resource  is stricly correlated to
the relevance of the resource value ;  Application may define its's own rules. .
Regarding "Location"  Object, if you don't need any value regarding location : just don't instantiate : it's an optional Object) . If it is instanciated, the Server knows few resources are mandatory (as Latitude), so an application could decide a silly value for Timestamp  (which is present) means the full information provided by this object instance  is irrelevant.
I don't say it is perfect, but it is the spirit

**Comment by ThGarnier** [comment]
no new remarks; I think this issue can be closed

**Comment by jvermillard** [comment]
> Regarding "Location" Object, if you don't need any value regarding location : just don't instantiate : it's an optional Object) 

So you mean when you have a correct location, you create the object and send a registration update ? and when the location is gone, poof registration update again ?

**Comment by sophokles73** [comment]
Following this thread of discussion I still do not know whether the @sbernard31 is right in assuming that `Server Public Key` and the others should actually **not** be mandatory.

@ThGarnier can you please make an explicit statement reagarding the original question at hand?

**Comment by hannestschofenig** [comment]
Reading through the discussion thread and also looking at the definition of mandatory I believe we need to at least clarify the definition of the mandatory field. Currently it is defined in such a way that one cannot be sure what 'support' means. From this discussion I guess the correct wording would be: 

> Mandatory: if this field is “Mandatory”, then the LWM2M Client MUST **implement** this Object. If this field is “Optional”, then the LWM2M Client SHOULD support this Object. Implementing an Object does not imply that it is actually used. 

(The term 'implement' here replaces 'support' in the paragraph above.)

Here is an example following the logic provided above: 

A LWM2M Client that is only ever going to use pre-shared secret credentials must implement all resources of the LWM2M Security object. It will only use those that are relevant for the pre-shared secret credentials.

What does this actually mean for an implementation? Does such a client have to be prepared to parse asymmetric crypto-related content, such as certificates? This would be a huge hit from an implementation point of view since such a client has to provide at least an ASN.1 library. Would it also have to then implement PK-based ciphersuites with DTLS since asymmetric credentials without the corresponding DTLS functionality wouldn't get the client very far. 

I am curious how companies have implemented this functionality on an IoT-device. I doubt that there is a company that has implemented all security modes. 

I believe that the best approach to deal with this problem (in case of the security object) is to do the following: 

 * make most of the resources optional (or more precisely conditional). 
 * add a new resource that indicates what mode (something like psk, raw public key, certificate) is actually supported. Alternatively, there has to be a way to return an error if the provided credentials cannot be used.

**Comment by boaks** [comment]
```
Does such a client have to be prepared to parse asymmetric crypto-related content, such as certificates?
```

Why should the client need to parse that? Do you mean "mandatory to implement" is equivalent to "mandatory to implement it in a **working** way"?

**Comment by ThGarnier** [comment]
The November 2016 TS 1.0 should bring a "definitive" :-) answer regarding the discussion on mandatory/option and other relative definitions => To Be Closed  (possibly reopen new issues then)

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above to check the November 2016 release and re-submit issues after this update

**Comment by sbernard31** [comment]
I comment this issue but let me know if it's better to create a new one. 

Recently, someone open an issue at Leshan https://github.com/eclipse/leshan/issues/1316 and we go back to this very old question. 

So I still don't understand what means mandatory.

Following https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/446 and [CREATE request description](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#8-2-3-0-823-Operation-on-Object) : 
> If the "Create" operation is permitted, the LwM2M Client MUST perform the instantiation of the Object only if all mandatory Resources are present in the "New Value" parameter (see Section [6. Interfaces](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-0-6-Interfaces)). If any of the mandatory Resources are not present, the LwM2M Client MUST send a "Bad Request" error code to the LwM2M Server.

I understand that mandatory means should be present in the payload.

So we go back to issue raise here : 
Should Server Public Key resource(4) of Security object (0) be mandatory ? 
If yes, what mean exacly mandatory and what does it mean concretely for a BOOTSTRAP WRITE request ?

I would really appreciate that we clarify this very old topic. :pray:

**Comment by davidahoward** [comment]
OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A

The "Server Public Key" Resource MUST NOT be used in the Pre-Shared Key mode.

https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#5-2-8-1-0-5281-Pre-Shared-Keys
