### ISSUE TITLE
Queue mode and REGISTER

### ISSUE THREAD

**Issue by fdur** [OpenMobileAlliance/OMA_LwM2M_for_Developers#80]
In 8.3 Queue mode:
3.  When the LWM2M Server receives a message from the Client (e.g. a notification or a registration update), 

I think that the Register needs to be added:
3.  When the LWM2M Server receives a message from the Client (e.g. a notification, a registration update or a registration),

**Comment by jvermillard** [comment]
:+1:

**Comment by boaks** [comment]
Adding "register" will bring up other issues:

- should messages be queued for not registered clients?
- should messages be removed from the queue for deregistered/removed clients?

5.3.1

"If the LWM2M Client sends a “Register” operation to the LWM2M Server even though the LWM2M Server has registration information of the LWM2M Client, the LWM2M Server removes the existing registration information and performs the new “Register” operation. 

So adding "register" seems for me to be a very strong indication, that queue mode is still specified very weak and therefore will be implemented application dependend what wll break interoperabilty.

**Comment by Megan-OMA** [comment]
@ThGarnier Will you please provide a final comment on why this issue is "To be closed" before we close it. Thank you!

**Comment by ThGarnier** [comment]
It is clear Queue mode functionality has to be globally revisited, before final approval (under study soon)

**Comment by hannestschofenig** [comment]
### Problem Statement: Re-Registration

A LWM2M client who had previously registered with its endpoint id X at the LWM2M server has lost its state (e.g., due to a reboot). On the server side there are messages queued for endpoint X. When the client re-registers with the LWM2M server are the previously queued messages delivered to the client?

### Proposed Resolution


Regarding a client sending a re-registration message after loosing state Section 5.3.1 mandates that the server must delete the previous registration records. Here is the relevant text: 


> If the LWM2M Client sends a “Register” operation to the LWM2M Server even though the LWM2M Server has registration information of the LWM2M Client, the LWM2M Server removes the existing registration information and performs the new “Register” operation. This situation happens when the LWM2M Client forgets the state of the LWM2M Server (e.g., factory reset).

However, in order to improve the application developer experience a LWM2M server should retain queued messages for such clients. This way an application does not have to re-send messages that have been queued before. 

### Problem Statement: Deregistration 

What happens to the queue when the client de-registers? 

### Proposed Resolution 

If a client deregisters or the registration expires then the queue should be deleted. 

### Problem Statement: Unregistered clients

Should messages be queued for not (yet) registered clients?

### Proposed Resolution 

A server may choose to queue such messages at its own discretion.

**Comment by fdur** [comment]
:+1: 
I totally agree with hannestschofenig's proposal

**Comment by balsmn** [comment]
I don't fully agree to @hannestschofenig proposal regarding **Re-Registration**.
What if the queued messages related to previous state of some resources on the LWM2M client (which is now lost due to a factory reset). In that case it doesn't make sense to send those messages to the LWM2M client. I think it should be left for the application layer to decide and LWM2M should simply remove all queued message when a re-registration happens.

**Comment by hannestschofenig** [comment]
@balsmn brings up a good point regarding the implications of sending queued messages to a newly restarted client. 

To summarize: When a LWM2M client restarts the question was what happens with already queued requests. The proposed resolution is to remove the existing registration information, and to delete all messages from the queue when the client re-registers. 

I also added the following statement: 

> However, in order to improve the application developer experience a LWM2M server should retain queued messages for such clients. This way an application does not have to re-send messages that have been queued before.

Whether sending queued messages to the rebooted LWM2M client makes sense or not will depend on a number of factors, many of them are unknown at the LWM2M layer itself. Leaving it to the application itself is also a bit tricky since we will to make some statements about what happens if a re-register message arrives while previous state exists.

I guess it will boil down to a somewhat clever interface between the LWM2M server and the application. This interface has to give the application the possibility to tell the LWM2M server whether messages in the queue should be deleted or not. 

If we apply that logic in an attempt to answer the question then the answer would be the following: 

> When the client re-registers with the LWM2M server then it is up to the application to decide whether any queued messages will be delivered to the client or deleted. In order for this to function, the LWM2M server has to give applications control over the management of the queue using some API, which is outside the scope of LWM2M. 

It feels a bit like postponing the answer to the question and to just push it outside the scope of LWM2M but if that's what folks have implemented or prefer to implement then it is fine for me. Ultimately what will be most important, I believe, is to ensure that the LWM2M client and the applications have a common view about the current state. Implementation and deployment experience will give us more insight over time what the best current practices are.

**Comment by sbernard31** [comment]
> What if the queued messages relate to previous state of some resources on the LWM2M client (which is now lost due to a factory reset). In that case it doesn't make sense to send those messages to the LWM2M client. 

This could also happen on registration update.

**Comment by hannestschofenig** [comment]
Covered in https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/115

**Comment by ThGarnier** [comment]
According to the last CR117 included in the Oct16 TS,  issue can be closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above re: October 2016 TS
