### ISSUE TITLE
Queue mode and timeout for offline

### ISSUE THREAD

**Issue by fdur** [OpenMobileAlliance/OMA_LwM2M_for_Developers#98]
In OMA-TS-LightweightM2M-V1_0-20151214-C, in Queue mode paragraph (8.3):
The LWM2M Client MUST wait at least **ACK_TIMEOUT** [COAP] seconds from the last CoAP message it sent to the LWM2M Server before intentionally going offline.

According to CoAP spec and CoAP retransmission, I think that the correct sentence is more:
The LWM2M Client MUST wait at least **MAX_TRANSMIT_WAIT** [COAP] seconds from the last CoAP message it sent to the LWM2M Server before intentionally going offline.

In fact, if a retransmission occurs on server side, the client can not receive the command from the server before the ACK_TIMEOUT timer expiry.

This need to be analyzed from my point of view.

With default values:
ACK_TIMEOUT = 2 seconds
MAX_TRANSMIT_WAIT = 93 seconds

**Comment by jpradocueva** [comment]
reported to the working group.

**Comment by boaks** [comment]
May be also related to:

https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/32

If the TS would clearly describe, which message flow (with ot without retries) was intended, it would be easier.

**Comment by msangoi** [comment]
MAX_TRANSMIT_SPAN seems to be a good candidate for this timeout value.

Note that all CoAP timeout values (ACK_TIMEOUT, MAX_RETRANSMIT...) are configurable and the client is not aware of the LWM2M server configuration. So there is no way to specify a value that can work for all clients.

**Comment by sophokles73** [comment]
From my point of view the overall intention of the client having to wait for some time before going to sleep again is to give the LWM2M Server a chance to send another message (request from the queue) to the LWM2M Client. The client should only go to sleep if it can be fairly sure that the server has no more messages for it (this time).

The MAX_TRANSMIT_WAIT value seems to be a suitable value from my point of view because it accounts for the time it takes to send the client's response to the last request to the server (incl. retransmissions) plus the time it takes to send the next request from the server to the client (incl. retransmissions). When the client therefore starts its timer when it sends its last response to the server, it can be pretty sure that the server does not have another message for the client after MAX_TRANSMIT_WAIT seconds.

On the other hand, I wonder if 93 secs (default value for MAX_TRANSMIT_WAIT) isn' t a little too long to wait for a constrained client running on a battery with an expected lifetime of several years ...

**Comment by boaks** [comment]
> Note that all CoAP timeout values (ACK_TIMEOUT, MAX_RETRANSMIT...) are configurable and the client is not aware of the LWM2M server configuration.

I'm not sure, if COAP works, if the configuration values are different.

**Comment by boaks** [comment]
For power efficency it may be better to use a "server ready" message and have the timeout just for some error cases.

**Comment by sophokles73** [comment]
Do you mean an explicit message that the server sends to the client in order to signal that it doesn't have any more messages in the queue to deliver to the client?
How long should the client wait for such a message? Isn't this effectively posing the same problem ;-)?

**Comment by boaks** [comment]
> Do you mean an explicit message that the server sends to the client in order to signal that it doesn't have any more messages in the queue to deliver to the client?

Yes

> How long should the client wait for such a message? Isn't this effectively posing the same problem ;-)?

MAX_RETRANSMIT, but this is just the error case. Usually the client gets this message as fast as the other messages, which is hopefully not MAX_RETRANSMIT.

LWM2M had a similiar issue with finishing the Bootstrap and sovled it there alse with an explicit finish message.
https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/35

**Comment by sophokles73** [comment]
> MAX_RETRANSMIT, but this is just the error case. Usually the client gets this message as fast as the other messages, which is hopefully not MAX_RETRANSMIT.

You mean MAX_TRANSMIT_SPAN, right? The max time (incl. retransmissions) it takes for a CON message to be delivered to the recipient ...

**Comment by boaks** [comment]
OK, sorry I copied the term incomplete. I would stay at "MAX_TRANSMIT_WAIT" from the first post.
But I would also just "recommend" it, and point out, that a shorter time will increase the risc for the request to be even more delayed (to the next online phase).

**Comment by sophokles73** [comment]
Ok, what's your opinion on the impact the long wait time would have on the device's battery lifetime? Is this an issue from your experience?

**Comment by boaks** [comment]
There are cases, where the device has longer periods of inactivity and frequently just wakes up to see, if there is some server side request (please, don't discuss "wakeup by sms"). Depending on the used "communication technic" this may just require some seconds and then waiting for 90s will stress a battery too much.
There are also cases, where the IoT-device is embedded in the "real device", say "car" or "truck". And if your IoT-device is intended to run from the "external" battery, you must comply to the rules of "real device". There for a flexible defintion will be required.

**Comment by hannestschofenig** [comment]
The use of ACK_TIMEOUT  in the following sentence is incorrect, as stated in the previous comments: 

"The LWM2M Client MUST wait at least ACK_TIMEOUT [COAP] seconds from the last CoAP message it sent to the LWM2M Server before intentionally going offline."

The corrected version is: 

"The LWM2M Client MUST wait at least MAX_TRANSMIT_WAIT [COAP] seconds from the last CoAP message it sent to the LWM2M Server before intentionally going offline."

The LWM2M client needs to give the LWM2M server some time before going to sleep again in order to send messages present in the queue. To allow the LWM2M server to signal that there are no pending messages in the queue the LWM2M server must send a non-confirmable CoAP POST to the “/qm” location path with empty payload. 

This allows the LWM2M client to immediately go to sleep after it has received this message. In case this finish indication is lost the LWM2M client will go to sleep after MAX_TRANSMIT_WAIT. 

For discussion: When the LWM2M client sends an update registration request after it has woken up the LWM2M server may include a flag/attribute in its response indicating to the LMW2M client that it has no pending messages. This would avoid an additional message from the server to the client.

**Comment by hannestschofenig** [comment]
Covered in https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/115

**Comment by ThGarnier** [comment]
According to the last CR117 included in the Oct16 TS,  issue can be closed

**Comment by fdur** [comment]
In CR117, in the figures 23 and 24, the ACK_TIMEOUT is still indicated (and also in OMA-TS-LightweightM2M-V1_0-20161007-D). It may be better to update it to MAX_TRANSMIT_WAIT

**Comment by dnav** [comment]
Text was corrected.
Figures need to be updated as pointed in #201
